# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './mw4/gui/widgets/bigPopup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BigPopup(object):
    def setupUi(self, BigPopup):
        BigPopup.setObjectName("BigPopup")
        BigPopup.resize(251, 107)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BigPopup.sizePolicy().hasHeightForWidth())
        BigPopup.setSizePolicy(sizePolicy)
        BigPopup.setMinimumSize(QtCore.QSize(200, 100))
        BigPopup.setMaximumSize(QtCore.QSize(400, 285))
        BigPopup.setSizeIncrement(QtCore.QSize(10, 10))
        BigPopup.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        BigPopup.setFont(font)
        self.gridLayout_2 = QtWidgets.QGridLayout(BigPopup)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mountBoot = QtWidgets.QPushButton(BigPopup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mountBoot.sizePolicy().hasHeightForWidth())
        self.mountBoot.setSizePolicy(sizePolicy)
        self.mountBoot.setObjectName("mountBoot")
        self.horizontalLayout.addWidget(self.mountBoot)
        self.mountStop = QtWidgets.QPushButton(BigPopup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mountStop.sizePolicy().hasHeightForWidth())
        self.mountStop.setSizePolicy(sizePolicy)
        self.mountStop.setObjectName("mountStop")
        self.horizontalLayout.addWidget(self.mountStop)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.virtualStop = QtWidgets.QPushButton(BigPopup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.virtualStop.sizePolicy().hasHeightForWidth())
        self.virtualStop.setSizePolicy(sizePolicy)
        self.virtualStop.setObjectName("virtualStop")
        self.gridLayout_2.addWidget(self.virtualStop, 2, 0, 1, 1)

        self.retranslateUi(BigPopup)
        QtCore.QMetaObject.connectSlotsByName(BigPopup)

    def retranslateUi(self, BigPopup):
        _translate = QtCore.QCoreApplication.translate
        BigPopup.setWindowTitle(_translate("BigPopup", "Device Setup"))
        self.mountBoot.setText(_translate("BigPopup", "Mount On"))
        self.mountStop.setText(_translate("BigPopup", "Mount Off"))
        self.virtualStop.setText(_translate("BigPopup", "Emergency Stop"))
        self.virtualStop.setProperty("color", _translate("BigPopup", "red"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BigPopup = QtWidgets.QWidget()
    ui = Ui_BigPopup()
    ui.setupUi(BigPopup)
    BigPopup.show()
    sys.exit(app.exec_())
