# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'devicePopup.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DevicePopup(object):
    def setupUi(self, DevicePopup):
        DevicePopup.setObjectName("DevicePopup")
        DevicePopup.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DevicePopup.sizePolicy().hasHeightForWidth())
        DevicePopup.setSizePolicy(sizePolicy)
        DevicePopup.setMinimumSize(QtCore.QSize(400, 300))
        DevicePopup.setMaximumSize(QtCore.QSize(400, 300))
        DevicePopup.setSizeIncrement(QtCore.QSize(10, 10))
        DevicePopup.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        DevicePopup.setFont(font)
        self.tab = QtWidgets.QTabWidget(DevicePopup)
        self.tab.setGeometry(QtCore.QRect(14, 5, 371, 256))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tab.setFont(font)
        self.tab.setObjectName("tab")
        self.indi = QtWidgets.QWidget()
        self.indi.setObjectName("indi")
        self.label_mountIP_3 = QtWidgets.QLabel(self.indi)
        self.label_mountIP_3.setGeometry(QtCore.QRect(10, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_mountIP_3.setFont(font)
        self.label_mountIP_3.setObjectName("label_mountIP_3")
        self.indiHost = QtWidgets.QLineEdit(self.indi)
        self.indiHost.setGeometry(QtCore.QRect(100, 40, 201, 21))
        self.indiHost.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.indiHost.setFont(font)
        self.indiHost.setMouseTracking(False)
        self.indiHost.setAcceptDrops(False)
        self.indiHost.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.indiHost.setMaxLength(50)
        self.indiHost.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.indiHost.setDragEnabled(True)
        self.indiHost.setReadOnly(False)
        self.indiHost.setObjectName("indiHost")
        self.label_mountIP_4 = QtWidgets.QLabel(self.indi)
        self.label_mountIP_4.setGeometry(QtCore.QRect(10, 70, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_mountIP_4.setFont(font)
        self.label_mountIP_4.setObjectName("label_mountIP_4")
        self.indiSearch = QtWidgets.QPushButton(self.indi)
        self.indiSearch.setGeometry(QtCore.QRect(305, 100, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.indiSearch.setFont(font)
        self.indiSearch.setObjectName("indiSearch")
        self.indiNameList = QtWidgets.QComboBox(self.indi)
        self.indiNameList.setGeometry(QtCore.QRect(100, 100, 201, 21))
        self.indiNameList.setObjectName("indiNameList")
        self.label_mountIP_5 = QtWidgets.QLabel(self.indi)
        self.label_mountIP_5.setGeometry(QtCore.QRect(10, 100, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_mountIP_5.setFont(font)
        self.label_mountIP_5.setObjectName("label_mountIP_5")
        self.indiMessages = QtWidgets.QCheckBox(self.indi)
        self.indiMessages.setGeometry(QtCore.QRect(100, 135, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.indiMessages.setFont(font)
        self.indiMessages.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.indiMessages.setChecked(False)
        self.indiMessages.setObjectName("indiMessages")
        self.indiPort = QtWidgets.QLineEdit(self.indi)
        self.indiPort.setGeometry(QtCore.QRect(100, 70, 50, 21))
        self.indiPort.setMinimumSize(QtCore.QSize(0, 0))
        self.indiPort.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.indiPort.setFont(font)
        self.indiPort.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.indiPort.setObjectName("indiPort")
        self.copyIndi = QtWidgets.QPushButton(self.indi)
        self.copyIndi.setGeometry(QtCore.QRect(100, 190, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.copyIndi.setFont(font)
        self.copyIndi.setObjectName("copyIndi")
        self.indiLoadConfig = QtWidgets.QCheckBox(self.indi)
        self.indiLoadConfig.setEnabled(False)
        self.indiLoadConfig.setGeometry(QtCore.QRect(100, 160, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.indiLoadConfig.setFont(font)
        self.indiLoadConfig.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.indiLoadConfig.setChecked(False)
        self.indiLoadConfig.setTristate(False)
        self.indiLoadConfig.setObjectName("indiLoadConfig")
        self.tab.addTab(self.indi, "")
        self.alpaca = QtWidgets.QWidget()
        self.alpaca.setObjectName("alpaca")
        self.label_mountIP_7 = QtWidgets.QLabel(self.alpaca)
        self.label_mountIP_7.setGeometry(QtCore.QRect(10, 100, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_mountIP_7.setFont(font)
        self.label_mountIP_7.setObjectName("label_mountIP_7")
        self.alpacaPort = QtWidgets.QLineEdit(self.alpaca)
        self.alpacaPort.setGeometry(QtCore.QRect(100, 70, 50, 21))
        self.alpacaPort.setMinimumSize(QtCore.QSize(0, 0))
        self.alpacaPort.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.alpacaPort.setFont(font)
        self.alpacaPort.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.alpacaPort.setObjectName("alpacaPort")
        self.label_mountIP_8 = QtWidgets.QLabel(self.alpaca)
        self.label_mountIP_8.setGeometry(QtCore.QRect(10, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_mountIP_8.setFont(font)
        self.label_mountIP_8.setObjectName("label_mountIP_8")
        self.label_mountIP_9 = QtWidgets.QLabel(self.alpaca)
        self.label_mountIP_9.setGeometry(QtCore.QRect(10, 10, 86, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_mountIP_9.setFont(font)
        self.label_mountIP_9.setObjectName("label_mountIP_9")
        self.label_mountIP_10 = QtWidgets.QLabel(self.alpaca)
        self.label_mountIP_10.setGeometry(QtCore.QRect(10, 70, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_mountIP_10.setFont(font)
        self.label_mountIP_10.setObjectName("label_mountIP_10")
        self.alpacaHost = QtWidgets.QLineEdit(self.alpaca)
        self.alpacaHost.setGeometry(QtCore.QRect(100, 40, 201, 21))
        self.alpacaHost.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.alpacaHost.setFont(font)
        self.alpacaHost.setMouseTracking(False)
        self.alpacaHost.setAcceptDrops(False)
        self.alpacaHost.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.alpacaHost.setMaxLength(50)
        self.alpacaHost.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.alpacaHost.setDragEnabled(True)
        self.alpacaHost.setReadOnly(False)
        self.alpacaHost.setObjectName("alpacaHost")
        self.copyAlpaca = QtWidgets.QPushButton(self.alpaca)
        self.copyAlpaca.setGeometry(QtCore.QRect(100, 190, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.copyAlpaca.setFont(font)
        self.copyAlpaca.setObjectName("copyAlpaca")
        self.alpacaProtocol = QtWidgets.QComboBox(self.alpaca)
        self.alpacaProtocol.setGeometry(QtCore.QRect(100, 10, 201, 21))
        self.alpacaProtocol.setObjectName("alpacaProtocol")
        self.alpacaProtocol.addItem("")
        self.alpacaProtocol.addItem("")
        self.label_mountIP_11 = QtWidgets.QLabel(self.alpaca)
        self.label_mountIP_11.setGeometry(QtCore.QRect(10, 130, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_mountIP_11.setFont(font)
        self.label_mountIP_11.setObjectName("label_mountIP_11")
        self.label_mountIP_12 = QtWidgets.QLabel(self.alpaca)
        self.label_mountIP_12.setGeometry(QtCore.QRect(10, 160, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_mountIP_12.setFont(font)
        self.label_mountIP_12.setObjectName("label_mountIP_12")
        self.alpacaUser = QtWidgets.QLineEdit(self.alpaca)
        self.alpacaUser.setGeometry(QtCore.QRect(100, 130, 201, 21))
        self.alpacaUser.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.alpacaUser.setFont(font)
        self.alpacaUser.setMouseTracking(False)
        self.alpacaUser.setAcceptDrops(False)
        self.alpacaUser.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.alpacaUser.setText("")
        self.alpacaUser.setMaxLength(50)
        self.alpacaUser.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.alpacaUser.setDragEnabled(True)
        self.alpacaUser.setReadOnly(False)
        self.alpacaUser.setObjectName("alpacaUser")
        self.alpacaPassword = QtWidgets.QLineEdit(self.alpaca)
        self.alpacaPassword.setGeometry(QtCore.QRect(100, 160, 201, 21))
        self.alpacaPassword.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.alpacaPassword.setFont(font)
        self.alpacaPassword.setMouseTracking(False)
        self.alpacaPassword.setAcceptDrops(False)
        self.alpacaPassword.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.alpacaPassword.setText("")
        self.alpacaPassword.setMaxLength(50)
        self.alpacaPassword.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.alpacaPassword.setDragEnabled(True)
        self.alpacaPassword.setReadOnly(False)
        self.alpacaPassword.setObjectName("alpacaPassword")
        self.alpacaNumber = QtWidgets.QSpinBox(self.alpaca)
        self.alpacaNumber.setGeometry(QtCore.QRect(100, 100, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.alpacaNumber.setFont(font)
        self.alpacaNumber.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.alpacaNumber.setObjectName("alpacaNumber")
        self.tab.addTab(self.alpaca, "")
        self.ok = QtWidgets.QPushButton(DevicePopup)
        self.ok.setGeometry(QtCore.QRect(315, 270, 75, 21))
        self.ok.setObjectName("ok")
        self.cancel = QtWidgets.QPushButton(DevicePopup)
        self.cancel.setGeometry(QtCore.QRect(230, 270, 75, 21))
        self.cancel.setObjectName("cancel")

        self.retranslateUi(DevicePopup)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DevicePopup)

    def retranslateUi(self, DevicePopup):
        _translate = QtCore.QCoreApplication.translate
        DevicePopup.setWindowTitle(_translate("DevicePopup", "Device Setup"))
        self.label_mountIP_3.setText(_translate("DevicePopup", "Host Address"))
        self.indiHost.setToolTip(_translate("DevicePopup", "IP address of INDI server, ip address and host names!"))
        self.indiHost.setText(_translate("DevicePopup", "localhost"))
        self.label_mountIP_4.setText(_translate("DevicePopup", "Host Port"))
        self.indiSearch.setToolTip(_translate("DevicePopup", "Search does list name of INDI devices of this certain type"))
        self.indiSearch.setText(_translate("DevicePopup", "Search"))
        self.label_mountIP_5.setText(_translate("DevicePopup", "Device Name"))
        self.indiMessages.setToolTip(_translate("DevicePopup", "When checked, the indi messages received will be shown inthe central message window"))
        self.indiMessages.setText(_translate("DevicePopup", "Show Messages"))
        self.indiPort.setToolTip(_translate("DevicePopup", "Port of INDI server"))
        self.indiPort.setText(_translate("DevicePopup", "7624"))
        self.copyIndi.setToolTip(_translate("DevicePopup", "Copy the host address, port and Show message settings to all INDI devices"))
        self.copyIndi.setText(_translate("DevicePopup", "Copy to all INDI devices"))
        self.indiLoadConfig.setToolTip(_translate("DevicePopup", "<html><head/><body><p>Checked if you would like to enable blind solver function in SGPro</p></body></html>"))
        self.indiLoadConfig.setText(_translate("DevicePopup", "Load configuration on start"))
        self.tab.setTabText(self.tab.indexOf(self.indi), _translate("DevicePopup", "INDI"))
        self.label_mountIP_7.setText(_translate("DevicePopup", "Device Number"))
        self.alpacaPort.setToolTip(_translate("DevicePopup", "Port of ALPACA server"))
        self.alpacaPort.setText(_translate("DevicePopup", "11111"))
        self.label_mountIP_8.setText(_translate("DevicePopup", "Host Address"))
        self.label_mountIP_9.setText(_translate("DevicePopup", "Host Protocol"))
        self.label_mountIP_10.setText(_translate("DevicePopup", "Host Port"))
        self.alpacaHost.setToolTip(_translate("DevicePopup", "<html><head/><body><p>IP address of INDI server, ip address and host names!</p></body></html>"))
        self.alpacaHost.setText(_translate("DevicePopup", "localhost"))
        self.copyAlpaca.setToolTip(_translate("DevicePopup", "Copy the protocol, host address, port, user and password settings to all ALPACA devices"))
        self.copyAlpaca.setText(_translate("DevicePopup", "Copy to all ALPACA devices"))
        self.alpacaProtocol.setToolTip(_translate("DevicePopup", "Choose the protocol type for ALPACA device"))
        self.alpacaProtocol.setItemText(0, _translate("DevicePopup", "http"))
        self.alpacaProtocol.setItemText(1, _translate("DevicePopup", "https"))
        self.label_mountIP_11.setText(_translate("DevicePopup", "User"))
        self.label_mountIP_12.setText(_translate("DevicePopup", "Password"))
        self.alpacaUser.setToolTip(_translate("DevicePopup", "User for alpaca device"))
        self.alpacaPassword.setToolTip(_translate("DevicePopup", "Passwor for alpaca device"))
        self.alpacaNumber.setToolTip(_translate("DevicePopup", "Device number configured on alpaca device"))
        self.tab.setTabText(self.tab.indexOf(self.alpaca), _translate("DevicePopup", "ALPACA"))
        self.ok.setText(_translate("DevicePopup", "OK"))
        self.cancel.setText(_translate("DevicePopup", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DevicePopup = QtWidgets.QWidget()
    ui = Ui_DevicePopup()
    ui.setupUi(DevicePopup)
    DevicePopup.show()
    sys.exit(app.exec_())
