# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'devicePopup.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDoubleSpinBox,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QTabWidget, QWidget)

class Ui_DevicePopup(object):
    def setupUi(self, DevicePopup):
        if not DevicePopup.objectName():
            DevicePopup.setObjectName(u"DevicePopup")
        DevicePopup.resize(460, 300)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DevicePopup.sizePolicy().hasHeightForWidth())
        DevicePopup.setSizePolicy(sizePolicy)
        DevicePopup.setMinimumSize(QSize(460, 300))
        DevicePopup.setMaximumSize(QSize(460, 300))
        DevicePopup.setSizeIncrement(QSize(10, 10))
        DevicePopup.setBaseSize(QSize(10, 10))
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(10)
        DevicePopup.setFont(font)
        self.tab = QTabWidget(DevicePopup)
        self.tab.setObjectName(u"tab")
        self.tab.setGeometry(QRect(80, 5, 371, 256))
        self.tab.setFont(font)
        self.tab.setElideMode(Qt.TextElideMode.ElideNone)
        self.alpaca = QWidget()
        self.alpaca.setObjectName(u"alpaca")
        self.label_mountIP_7 = QLabel(self.alpaca)
        self.label_mountIP_7.setObjectName(u"label_mountIP_7")
        self.label_mountIP_7.setGeometry(QRect(10, 100, 91, 21))
        self.label_mountIP_7.setFont(font)
        self.alpacaPort = QLineEdit(self.alpaca)
        self.alpacaPort.setObjectName(u"alpacaPort")
        self.alpacaPort.setGeometry(QRect(100, 70, 50, 21))
        self.alpacaPort.setMinimumSize(QSize(0, 0))
        self.alpacaPort.setMaximumSize(QSize(50, 16777215))
        self.alpacaPort.setFont(font)
        self.alpacaPort.setFrame(False)
        self.alpacaPort.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_mountIP_8 = QLabel(self.alpaca)
        self.label_mountIP_8.setObjectName(u"label_mountIP_8")
        self.label_mountIP_8.setGeometry(QRect(10, 40, 81, 21))
        self.label_mountIP_8.setFont(font)
        self.label_mountIP_10 = QLabel(self.alpaca)
        self.label_mountIP_10.setObjectName(u"label_mountIP_10")
        self.label_mountIP_10.setGeometry(QRect(10, 70, 81, 21))
        self.label_mountIP_10.setFont(font)
        self.alpacaHostAddress = QLineEdit(self.alpaca)
        self.alpacaHostAddress.setObjectName(u"alpacaHostAddress")
        self.alpacaHostAddress.setGeometry(QRect(100, 40, 201, 21))
        self.alpacaHostAddress.setMinimumSize(QSize(0, 0))
        font1 = QFont()
        font1.setFamilies([u"Arial"])
        font1.setPointSize(10)
        font1.setBold(False)
        self.alpacaHostAddress.setFont(font1)
        self.alpacaHostAddress.setMouseTracking(False)
        self.alpacaHostAddress.setAcceptDrops(False)
        self.alpacaHostAddress.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.alpacaHostAddress.setMaxLength(50)
        self.alpacaHostAddress.setFrame(False)
        self.alpacaHostAddress.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.alpacaHostAddress.setDragEnabled(True)
        self.alpacaHostAddress.setReadOnly(False)
        self.label_mountIP_11 = QLabel(self.alpaca)
        self.label_mountIP_11.setObjectName(u"label_mountIP_11")
        self.label_mountIP_11.setGeometry(QRect(10, 130, 91, 21))
        self.label_mountIP_11.setFont(font)
        self.label_mountIP_12 = QLabel(self.alpaca)
        self.label_mountIP_12.setObjectName(u"label_mountIP_12")
        self.label_mountIP_12.setGeometry(QRect(10, 160, 91, 21))
        self.label_mountIP_12.setFont(font)
        self.alpacaUser = QLineEdit(self.alpaca)
        self.alpacaUser.setObjectName(u"alpacaUser")
        self.alpacaUser.setGeometry(QRect(100, 130, 201, 21))
        self.alpacaUser.setMinimumSize(QSize(0, 0))
        self.alpacaUser.setFont(font1)
        self.alpacaUser.setMouseTracking(False)
        self.alpacaUser.setAcceptDrops(False)
        self.alpacaUser.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.alpacaUser.setMaxLength(50)
        self.alpacaUser.setFrame(False)
        self.alpacaUser.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.alpacaUser.setDragEnabled(True)
        self.alpacaUser.setReadOnly(False)
        self.alpacaPassword = QLineEdit(self.alpaca)
        self.alpacaPassword.setObjectName(u"alpacaPassword")
        self.alpacaPassword.setGeometry(QRect(100, 160, 201, 21))
        self.alpacaPassword.setMinimumSize(QSize(0, 0))
        self.alpacaPassword.setFont(font1)
        self.alpacaPassword.setMouseTracking(False)
        self.alpacaPassword.setAcceptDrops(False)
        self.alpacaPassword.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.alpacaPassword.setMaxLength(50)
        self.alpacaPassword.setFrame(False)
        self.alpacaPassword.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.alpacaPassword.setDragEnabled(True)
        self.alpacaPassword.setReadOnly(False)
        self.alpacaDeviceList = QComboBox(self.alpaca)
        self.alpacaDeviceList.setObjectName(u"alpacaDeviceList")
        self.alpacaDeviceList.setGeometry(QRect(100, 100, 201, 21))
        self.alpacaCopyConfig = QCheckBox(self.alpaca)
        self.alpacaCopyConfig.setObjectName(u"alpacaCopyConfig")
        self.alpacaCopyConfig.setEnabled(True)
        self.alpacaCopyConfig.setGeometry(QRect(100, 190, 201, 20))
        self.alpacaCopyConfig.setFont(font)
        self.alpacaCopyConfig.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.alpacaCopyConfig.setChecked(False)
        self.alpacaCopyConfig.setTristate(False)
        self.alpacaDiscover = QPushButton(self.alpaca)
        self.alpacaDiscover.setObjectName(u"alpacaDiscover")
        self.alpacaDiscover.setGeometry(QRect(305, 100, 51, 21))
        self.alpacaDiscover.setFont(font)
        self.alpacaUpdateRate = QDoubleSpinBox(self.alpaca)
        self.alpacaUpdateRate.setObjectName(u"alpacaUpdateRate")
        self.alpacaUpdateRate.setGeometry(QRect(220, 70, 62, 21))
        self.alpacaUpdateRate.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.alpacaUpdateRate.setDecimals(0)
        self.alpacaUpdateRate.setMinimum(1000.000000000000000)
        self.alpacaUpdateRate.setMaximum(30000.000000000000000)
        self.alpacaUpdateRate.setSingleStep(100.000000000000000)
        self.alpacaUpdateRate.setValue(1000.000000000000000)
        self.label_mountIP_22 = QLabel(self.alpaca)
        self.label_mountIP_22.setObjectName(u"label_mountIP_22")
        self.label_mountIP_22.setGeometry(QRect(190, 70, 31, 21))
        self.label_mountIP_22.setFont(font)
        self.label_mountIP_23 = QLabel(self.alpaca)
        self.label_mountIP_23.setObjectName(u"label_mountIP_23")
        self.label_mountIP_23.setGeometry(QRect(285, 70, 26, 21))
        self.label_mountIP_23.setFont(font)
        self.tab.addTab(self.alpaca, "")
        self.ascom = QWidget()
        self.ascom.setObjectName(u"ascom")
        self.ascomSelector = QPushButton(self.ascom)
        self.ascomSelector.setObjectName(u"ascomSelector")
        self.ascomSelector.setGeometry(QRect(100, 190, 201, 21))
        self.ascomSelector.setFont(font)
        self.label_mountIP_15 = QLabel(self.ascom)
        self.label_mountIP_15.setObjectName(u"label_mountIP_15")
        self.label_mountIP_15.setGeometry(QRect(10, 100, 91, 21))
        self.label_mountIP_15.setFont(font)
        self.ascomDevice = QLineEdit(self.ascom)
        self.ascomDevice.setObjectName(u"ascomDevice")
        self.ascomDevice.setGeometry(QRect(100, 100, 196, 21))
        self.ascomDevice.setMinimumSize(QSize(0, 0))
        self.ascomDevice.setFont(font1)
        self.ascomDevice.setMouseTracking(False)
        self.ascomDevice.setAcceptDrops(False)
        self.ascomDevice.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.ascomDevice.setMaxLength(50)
        self.ascomDevice.setFrame(False)
        self.ascomDevice.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ascomDevice.setDragEnabled(True)
        self.ascomDevice.setReadOnly(False)
        self.tab.addTab(self.ascom, "")
        self.sgpro = QWidget()
        self.sgpro.setObjectName(u"sgpro")
        self.label_mountIP_20 = QLabel(self.sgpro)
        self.label_mountIP_20.setObjectName(u"label_mountIP_20")
        self.label_mountIP_20.setGeometry(QRect(10, 100, 91, 21))
        self.label_mountIP_20.setFont(font)
        self.sgproDeviceList = QComboBox(self.sgpro)
        self.sgproDeviceList.setObjectName(u"sgproDeviceList")
        self.sgproDeviceList.setGeometry(QRect(100, 100, 201, 21))
        self.tab.addTab(self.sgpro, "")
        self.nina = QWidget()
        self.nina.setObjectName(u"nina")
        self.ninaDeviceList = QComboBox(self.nina)
        self.ninaDeviceList.setObjectName(u"ninaDeviceList")
        self.ninaDeviceList.setGeometry(QRect(100, 100, 201, 21))
        self.label_mountIP_21 = QLabel(self.nina)
        self.label_mountIP_21.setObjectName(u"label_mountIP_21")
        self.label_mountIP_21.setGeometry(QRect(10, 100, 91, 21))
        self.label_mountIP_21.setFont(font)
        self.tab.addTab(self.nina, "")
        self.indi = QWidget()
        self.indi.setObjectName(u"indi")
        self.label_mountIP_3 = QLabel(self.indi)
        self.label_mountIP_3.setObjectName(u"label_mountIP_3")
        self.label_mountIP_3.setGeometry(QRect(10, 40, 81, 21))
        self.label_mountIP_3.setFont(font)
        self.indiHostAddress = QLineEdit(self.indi)
        self.indiHostAddress.setObjectName(u"indiHostAddress")
        self.indiHostAddress.setGeometry(QRect(100, 40, 201, 21))
        self.indiHostAddress.setMinimumSize(QSize(0, 0))
        self.indiHostAddress.setFont(font1)
        self.indiHostAddress.setMouseTracking(False)
        self.indiHostAddress.setAcceptDrops(False)
        self.indiHostAddress.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.indiHostAddress.setMaxLength(50)
        self.indiHostAddress.setFrame(False)
        self.indiHostAddress.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.indiHostAddress.setDragEnabled(True)
        self.indiHostAddress.setReadOnly(False)
        self.label_mountIP_4 = QLabel(self.indi)
        self.label_mountIP_4.setObjectName(u"label_mountIP_4")
        self.label_mountIP_4.setGeometry(QRect(10, 70, 81, 21))
        self.label_mountIP_4.setFont(font)
        self.indiDiscover = QPushButton(self.indi)
        self.indiDiscover.setObjectName(u"indiDiscover")
        self.indiDiscover.setGeometry(QRect(305, 100, 51, 21))
        self.indiDiscover.setFont(font)
        self.indiDeviceList = QComboBox(self.indi)
        self.indiDeviceList.setObjectName(u"indiDeviceList")
        self.indiDeviceList.setGeometry(QRect(100, 100, 201, 21))
        self.label_mountIP_5 = QLabel(self.indi)
        self.label_mountIP_5.setObjectName(u"label_mountIP_5")
        self.label_mountIP_5.setGeometry(QRect(10, 100, 81, 21))
        self.label_mountIP_5.setFont(font)
        self.indiMessages = QCheckBox(self.indi)
        self.indiMessages.setObjectName(u"indiMessages")
        self.indiMessages.setGeometry(QRect(100, 135, 201, 20))
        self.indiMessages.setFont(font)
        self.indiMessages.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.indiMessages.setChecked(False)
        self.indiPort = QLineEdit(self.indi)
        self.indiPort.setObjectName(u"indiPort")
        self.indiPort.setGeometry(QRect(100, 70, 50, 21))
        self.indiPort.setMinimumSize(QSize(0, 0))
        self.indiPort.setMaximumSize(QSize(50, 16777215))
        self.indiPort.setFont(font)
        self.indiPort.setFrame(False)
        self.indiPort.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.indiLoadConfig = QCheckBox(self.indi)
        self.indiLoadConfig.setObjectName(u"indiLoadConfig")
        self.indiLoadConfig.setEnabled(True)
        self.indiLoadConfig.setGeometry(QRect(100, 160, 201, 20))
        self.indiLoadConfig.setFont(font)
        self.indiLoadConfig.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.indiLoadConfig.setChecked(False)
        self.indiLoadConfig.setTristate(False)
        self.indiCopyConfig = QCheckBox(self.indi)
        self.indiCopyConfig.setObjectName(u"indiCopyConfig")
        self.indiCopyConfig.setEnabled(True)
        self.indiCopyConfig.setGeometry(QRect(100, 185, 201, 20))
        self.indiCopyConfig.setFont(font)
        self.indiCopyConfig.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.indiCopyConfig.setChecked(False)
        self.indiCopyConfig.setTristate(False)
        self.label_mountIP_9 = QLabel(self.indi)
        self.label_mountIP_9.setObjectName(u"label_mountIP_9")
        self.label_mountIP_9.setGeometry(QRect(185, 70, 31, 21))
        self.label_mountIP_9.setFont(font)
        self.label_mountIP_13 = QLabel(self.indi)
        self.label_mountIP_13.setObjectName(u"label_mountIP_13")
        self.label_mountIP_13.setGeometry(QRect(280, 70, 26, 21))
        self.label_mountIP_13.setFont(font)
        self.indiUpdateRate = QDoubleSpinBox(self.indi)
        self.indiUpdateRate.setObjectName(u"indiUpdateRate")
        self.indiUpdateRate.setGeometry(QRect(215, 70, 62, 21))
        self.indiUpdateRate.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.indiUpdateRate.setDecimals(0)
        self.indiUpdateRate.setMinimum(1000.000000000000000)
        self.indiUpdateRate.setMaximum(30000.000000000000000)
        self.indiUpdateRate.setSingleStep(100.000000000000000)
        self.indiUpdateRate.setValue(1000.000000000000000)
        self.tab.addTab(self.indi, "")
        self.astrometry = QWidget()
        self.astrometry.setObjectName(u"astrometry")
        self.label_mountIP_14 = QLabel(self.astrometry)
        self.label_mountIP_14.setObjectName(u"label_mountIP_14")
        self.label_mountIP_14.setGeometry(QRect(10, 65, 146, 21))
        self.label_mountIP_14.setFont(font)
        self.astrometryIndexPath = QLineEdit(self.astrometry)
        self.astrometryIndexPath.setObjectName(u"astrometryIndexPath")
        self.astrometryIndexPath.setEnabled(True)
        self.astrometryIndexPath.setGeometry(QRect(10, 90, 346, 21))
        self.astrometryIndexPath.setMinimumSize(QSize(0, 0))
        self.astrometryIndexPath.setFont(font1)
        self.astrometryIndexPath.setMouseTracking(False)
        self.astrometryIndexPath.setAcceptDrops(False)
        self.astrometryIndexPath.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.astrometryIndexPath.setMaxLength(100)
        self.astrometryIndexPath.setFrame(False)
        self.astrometryIndexPath.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.astrometryIndexPath.setDragEnabled(True)
        self.astrometryIndexPath.setReadOnly(False)
        self.selectAstrometryIndexPath = QPushButton(self.astrometry)
        self.selectAstrometryIndexPath.setObjectName(u"selectAstrometryIndexPath")
        self.selectAstrometryIndexPath.setGeometry(QRect(310, 65, 46, 21))
        self.selectAstrometryIndexPath.setFont(font)
        self.astrometryDeviceList = QComboBox(self.astrometry)
        self.astrometryDeviceList.setObjectName(u"astrometryDeviceList")
        self.astrometryDeviceList.setGeometry(QRect(100, 120, 201, 21))
        self.label_mountIP_6 = QLabel(self.astrometry)
        self.label_mountIP_6.setObjectName(u"label_mountIP_6")
        self.label_mountIP_6.setGeometry(QRect(10, 120, 81, 21))
        self.label_mountIP_6.setFont(font)
        self.label_316 = QLabel(self.astrometry)
        self.label_316.setObjectName(u"label_316")
        self.label_316.setGeometry(QRect(10, 180, 86, 21))
        self.label_316.setFont(font1)
        self.astrometrySearchRadius = QDoubleSpinBox(self.astrometry)
        self.astrometrySearchRadius.setObjectName(u"astrometrySearchRadius")
        self.astrometrySearchRadius.setGeometry(QRect(100, 150, 46, 21))
        self.astrometrySearchRadius.setFont(font1)
        self.astrometrySearchRadius.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.astrometrySearchRadius.setDecimals(0)
        self.astrometrySearchRadius.setMinimum(1.000000000000000)
        self.astrometrySearchRadius.setMaximum(180.000000000000000)
        self.astrometrySearchRadius.setSingleStep(5.000000000000000)
        self.astrometrySearchRadius.setValue(30.000000000000000)
        self.astrometryTimeout = QDoubleSpinBox(self.astrometry)
        self.astrometryTimeout.setObjectName(u"astrometryTimeout")
        self.astrometryTimeout.setGeometry(QRect(100, 180, 46, 21))
        self.astrometryTimeout.setFont(font1)
        self.astrometryTimeout.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.astrometryTimeout.setDecimals(0)
        self.astrometryTimeout.setMinimum(2.000000000000000)
        self.astrometryTimeout.setMaximum(300.000000000000000)
        self.astrometryTimeout.setSingleStep(5.000000000000000)
        self.astrometryTimeout.setValue(30.000000000000000)
        self.label_315 = QLabel(self.astrometry)
        self.label_315.setObjectName(u"label_315")
        self.label_315.setGeometry(QRect(10, 150, 86, 21))
        self.label_315.setFont(font1)
        self.label_317 = QLabel(self.astrometry)
        self.label_317.setObjectName(u"label_317")
        self.label_317.setGeometry(QRect(150, 180, 21, 21))
        self.label_317.setFont(font1)
        self.label_318 = QLabel(self.astrometry)
        self.label_318.setObjectName(u"label_318")
        self.label_318.setGeometry(QRect(150, 150, 61, 21))
        self.label_318.setFont(font1)
        self.label_mountIP_17 = QLabel(self.astrometry)
        self.label_mountIP_17.setObjectName(u"label_mountIP_17")
        self.label_mountIP_17.setGeometry(QRect(10, 10, 106, 21))
        self.label_mountIP_17.setFont(font)
        self.astrometryAppPath = QLineEdit(self.astrometry)
        self.astrometryAppPath.setObjectName(u"astrometryAppPath")
        self.astrometryAppPath.setEnabled(True)
        self.astrometryAppPath.setGeometry(QRect(10, 35, 346, 21))
        self.astrometryAppPath.setMinimumSize(QSize(0, 0))
        self.astrometryAppPath.setFont(font1)
        self.astrometryAppPath.setMouseTracking(False)
        self.astrometryAppPath.setAcceptDrops(False)
        self.astrometryAppPath.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.astrometryAppPath.setMaxLength(100)
        self.astrometryAppPath.setFrame(False)
        self.astrometryAppPath.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.astrometryAppPath.setDragEnabled(True)
        self.astrometryAppPath.setReadOnly(False)
        self.selectAstrometryAppPath = QPushButton(self.astrometry)
        self.selectAstrometryAppPath.setObjectName(u"selectAstrometryAppPath")
        self.selectAstrometryAppPath.setEnabled(True)
        self.selectAstrometryAppPath.setGeometry(QRect(310, 10, 46, 21))
        self.selectAstrometryAppPath.setFont(font)
        self.tab.addTab(self.astrometry, "")
        self.astap = QWidget()
        self.astap.setObjectName(u"astap")
        self.label_mountIP_16 = QLabel(self.astap)
        self.label_mountIP_16.setObjectName(u"label_mountIP_16")
        self.label_mountIP_16.setGeometry(QRect(10, 120, 81, 21))
        self.label_mountIP_16.setFont(font)
        self.astapTimeout = QDoubleSpinBox(self.astap)
        self.astapTimeout.setObjectName(u"astapTimeout")
        self.astapTimeout.setGeometry(QRect(100, 180, 46, 21))
        self.astapTimeout.setFont(font1)
        self.astapTimeout.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.astapTimeout.setDecimals(0)
        self.astapTimeout.setMinimum(2.000000000000000)
        self.astapTimeout.setMaximum(300.000000000000000)
        self.astapTimeout.setSingleStep(5.000000000000000)
        self.astapTimeout.setValue(30.000000000000000)
        self.astapSearchRadius = QDoubleSpinBox(self.astap)
        self.astapSearchRadius.setObjectName(u"astapSearchRadius")
        self.astapSearchRadius.setGeometry(QRect(100, 150, 46, 21))
        self.astapSearchRadius.setFont(font1)
        self.astapSearchRadius.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.astapSearchRadius.setDecimals(0)
        self.astapSearchRadius.setMinimum(1.000000000000000)
        self.astapSearchRadius.setMaximum(180.000000000000000)
        self.astapSearchRadius.setSingleStep(5.000000000000000)
        self.astapSearchRadius.setValue(30.000000000000000)
        self.label_319 = QLabel(self.astap)
        self.label_319.setObjectName(u"label_319")
        self.label_319.setGeometry(QRect(10, 180, 86, 21))
        self.label_319.setFont(font1)
        self.label_320 = QLabel(self.astap)
        self.label_320.setObjectName(u"label_320")
        self.label_320.setGeometry(QRect(10, 150, 86, 21))
        self.label_320.setFont(font1)
        self.label_321 = QLabel(self.astap)
        self.label_321.setObjectName(u"label_321")
        self.label_321.setGeometry(QRect(150, 180, 21, 21))
        self.label_321.setFont(font1)
        self.label_322 = QLabel(self.astap)
        self.label_322.setObjectName(u"label_322")
        self.label_322.setGeometry(QRect(150, 150, 206, 21))
        self.label_322.setFont(font1)
        self.astapIndexPath = QLineEdit(self.astap)
        self.astapIndexPath.setObjectName(u"astapIndexPath")
        self.astapIndexPath.setEnabled(True)
        self.astapIndexPath.setGeometry(QRect(10, 90, 346, 21))
        self.astapIndexPath.setMinimumSize(QSize(0, 0))
        self.astapIndexPath.setFont(font1)
        self.astapIndexPath.setMouseTracking(False)
        self.astapIndexPath.setAcceptDrops(False)
        self.astapIndexPath.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.astapIndexPath.setMaxLength(100)
        self.astapIndexPath.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.astapIndexPath.setDragEnabled(True)
        self.astapIndexPath.setReadOnly(False)
        self.astapAppPath = QLineEdit(self.astap)
        self.astapAppPath.setObjectName(u"astapAppPath")
        self.astapAppPath.setEnabled(True)
        self.astapAppPath.setGeometry(QRect(10, 35, 346, 21))
        self.astapAppPath.setMinimumSize(QSize(0, 0))
        self.astapAppPath.setFont(font1)
        self.astapAppPath.setMouseTracking(False)
        self.astapAppPath.setAcceptDrops(False)
        self.astapAppPath.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.astapAppPath.setMaxLength(100)
        self.astapAppPath.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.astapAppPath.setDragEnabled(True)
        self.astapAppPath.setReadOnly(False)
        self.selectAstapIndexPath = QPushButton(self.astap)
        self.selectAstapIndexPath.setObjectName(u"selectAstapIndexPath")
        self.selectAstapIndexPath.setEnabled(True)
        self.selectAstapIndexPath.setGeometry(QRect(310, 65, 46, 21))
        self.selectAstapIndexPath.setFont(font)
        self.selectAstapAppPath = QPushButton(self.astap)
        self.selectAstapAppPath.setObjectName(u"selectAstapAppPath")
        self.selectAstapAppPath.setEnabled(True)
        self.selectAstapAppPath.setGeometry(QRect(310, 10, 46, 21))
        self.selectAstapAppPath.setFont(font)
        self.astapDeviceList = QComboBox(self.astap)
        self.astapDeviceList.setObjectName(u"astapDeviceList")
        self.astapDeviceList.setGeometry(QRect(100, 120, 201, 21))
        self.label_mountIP_18 = QLabel(self.astap)
        self.label_mountIP_18.setObjectName(u"label_mountIP_18")
        self.label_mountIP_18.setGeometry(QRect(10, 65, 146, 21))
        self.label_mountIP_18.setFont(font)
        self.label_mountIP_19 = QLabel(self.astap)
        self.label_mountIP_19.setObjectName(u"label_mountIP_19")
        self.label_mountIP_19.setGeometry(QRect(10, 10, 106, 21))
        self.label_mountIP_19.setFont(font)
        self.tab.addTab(self.astap, "")
        self.watney = QWidget()
        self.watney.setObjectName(u"watney")
        self.label_323 = QLabel(self.watney)
        self.label_323.setObjectName(u"label_323")
        self.label_323.setGeometry(QRect(10, 150, 86, 21))
        self.label_323.setFont(font1)
        self.selectWatneyIndexPath = QPushButton(self.watney)
        self.selectWatneyIndexPath.setObjectName(u"selectWatneyIndexPath")
        self.selectWatneyIndexPath.setEnabled(True)
        self.selectWatneyIndexPath.setGeometry(QRect(310, 65, 46, 21))
        self.selectWatneyIndexPath.setFont(font)
        self.watneyTimeout = QDoubleSpinBox(self.watney)
        self.watneyTimeout.setObjectName(u"watneyTimeout")
        self.watneyTimeout.setGeometry(QRect(100, 180, 46, 21))
        self.watneyTimeout.setFont(font1)
        self.watneyTimeout.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.watneyTimeout.setDecimals(0)
        self.watneyTimeout.setMinimum(2.000000000000000)
        self.watneyTimeout.setMaximum(300.000000000000000)
        self.watneyTimeout.setSingleStep(5.000000000000000)
        self.watneyTimeout.setValue(30.000000000000000)
        self.label_324 = QLabel(self.watney)
        self.label_324.setObjectName(u"label_324")
        self.label_324.setGeometry(QRect(10, 180, 86, 21))
        self.label_324.setFont(font1)
        self.label_mountIP_24 = QLabel(self.watney)
        self.label_mountIP_24.setObjectName(u"label_mountIP_24")
        self.label_mountIP_24.setGeometry(QRect(10, 65, 146, 21))
        self.label_mountIP_24.setFont(font)
        self.watneyAppPath = QLineEdit(self.watney)
        self.watneyAppPath.setObjectName(u"watneyAppPath")
        self.watneyAppPath.setEnabled(True)
        self.watneyAppPath.setGeometry(QRect(10, 35, 346, 21))
        self.watneyAppPath.setMinimumSize(QSize(0, 0))
        self.watneyAppPath.setFont(font1)
        self.watneyAppPath.setMouseTracking(False)
        self.watneyAppPath.setAcceptDrops(False)
        self.watneyAppPath.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.watneyAppPath.setMaxLength(100)
        self.watneyAppPath.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.watneyAppPath.setDragEnabled(True)
        self.watneyAppPath.setReadOnly(False)
        self.label_325 = QLabel(self.watney)
        self.label_325.setObjectName(u"label_325")
        self.label_325.setGeometry(QRect(150, 150, 206, 21))
        self.label_325.setFont(font1)
        self.label_326 = QLabel(self.watney)
        self.label_326.setObjectName(u"label_326")
        self.label_326.setGeometry(QRect(150, 180, 21, 21))
        self.label_326.setFont(font1)
        self.watneySearchRadius = QDoubleSpinBox(self.watney)
        self.watneySearchRadius.setObjectName(u"watneySearchRadius")
        self.watneySearchRadius.setGeometry(QRect(100, 150, 46, 21))
        self.watneySearchRadius.setFont(font1)
        self.watneySearchRadius.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.watneySearchRadius.setDecimals(0)
        self.watneySearchRadius.setMinimum(1.000000000000000)
        self.watneySearchRadius.setMaximum(180.000000000000000)
        self.watneySearchRadius.setSingleStep(5.000000000000000)
        self.watneySearchRadius.setValue(30.000000000000000)
        self.watneyIndexPath = QLineEdit(self.watney)
        self.watneyIndexPath.setObjectName(u"watneyIndexPath")
        self.watneyIndexPath.setEnabled(True)
        self.watneyIndexPath.setGeometry(QRect(10, 90, 346, 21))
        self.watneyIndexPath.setMinimumSize(QSize(0, 0))
        self.watneyIndexPath.setFont(font1)
        self.watneyIndexPath.setMouseTracking(False)
        self.watneyIndexPath.setAcceptDrops(False)
        self.watneyIndexPath.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.watneyIndexPath.setMaxLength(100)
        self.watneyIndexPath.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.watneyIndexPath.setDragEnabled(True)
        self.watneyIndexPath.setReadOnly(False)
        self.watneyDeviceList = QComboBox(self.watney)
        self.watneyDeviceList.setObjectName(u"watneyDeviceList")
        self.watneyDeviceList.setGeometry(QRect(100, 120, 201, 21))
        self.label_mountIP_25 = QLabel(self.watney)
        self.label_mountIP_25.setObjectName(u"label_mountIP_25")
        self.label_mountIP_25.setGeometry(QRect(10, 120, 81, 21))
        self.label_mountIP_25.setFont(font)
        self.label_mountIP_26 = QLabel(self.watney)
        self.label_mountIP_26.setObjectName(u"label_mountIP_26")
        self.label_mountIP_26.setGeometry(QRect(10, 10, 106, 21))
        self.label_mountIP_26.setFont(font)
        self.selectWatneyAppPath = QPushButton(self.watney)
        self.selectWatneyAppPath.setObjectName(u"selectWatneyAppPath")
        self.selectWatneyAppPath.setEnabled(True)
        self.selectWatneyAppPath.setGeometry(QRect(310, 10, 46, 21))
        self.selectWatneyAppPath.setFont(font)
        self.tab.addTab(self.watney, "")
        self.onlineWeather = QWidget()
        self.onlineWeather.setObjectName(u"onlineWeather")
        self.label_mountIP_33 = QLabel(self.onlineWeather)
        self.label_mountIP_33.setObjectName(u"label_mountIP_33")
        self.label_mountIP_33.setGeometry(QRect(10, 40, 81, 21))
        self.label_mountIP_33.setFont(font)
        self.onlineWeatherHostAddress = QLineEdit(self.onlineWeather)
        self.onlineWeatherHostAddress.setObjectName(u"onlineWeatherHostAddress")
        self.onlineWeatherHostAddress.setEnabled(True)
        self.onlineWeatherHostAddress.setGeometry(QRect(100, 40, 241, 21))
        self.onlineWeatherHostAddress.setMinimumSize(QSize(0, 0))
        self.onlineWeatherHostAddress.setFont(font1)
        self.onlineWeatherHostAddress.setMouseTracking(False)
        self.onlineWeatherHostAddress.setAcceptDrops(False)
        self.onlineWeatherHostAddress.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.onlineWeatherHostAddress.setMaxLength(50)
        self.onlineWeatherHostAddress.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.onlineWeatherHostAddress.setDragEnabled(True)
        self.onlineWeatherHostAddress.setReadOnly(False)
        self.onlineWeatherApiKey = QLineEdit(self.onlineWeather)
        self.onlineWeatherApiKey.setObjectName(u"onlineWeatherApiKey")
        self.onlineWeatherApiKey.setGeometry(QRect(100, 70, 241, 21))
        self.onlineWeatherApiKey.setMinimumSize(QSize(0, 0))
        self.onlineWeatherApiKey.setFont(font1)
        self.onlineWeatherApiKey.setMouseTracking(False)
        self.onlineWeatherApiKey.setAcceptDrops(False)
        self.onlineWeatherApiKey.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.onlineWeatherApiKey.setMaxLength(50)
        self.onlineWeatherApiKey.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.onlineWeatherApiKey.setDragEnabled(True)
        self.onlineWeatherApiKey.setReadOnly(False)
        self.label_mountIP_34 = QLabel(self.onlineWeather)
        self.label_mountIP_34.setObjectName(u"label_mountIP_34")
        self.label_mountIP_34.setGeometry(QRect(10, 70, 81, 21))
        self.label_mountIP_34.setFont(font)
        self.tab.addTab(self.onlineWeather, "")
        self.seeing = QWidget()
        self.seeing.setObjectName(u"seeing")
        self.label_mountIP_38 = QLabel(self.seeing)
        self.label_mountIP_38.setObjectName(u"label_mountIP_38")
        self.label_mountIP_38.setGeometry(QRect(15, 70, 81, 21))
        self.label_mountIP_38.setFont(font)
        self.seeingWeatherHostAddress = QLineEdit(self.seeing)
        self.seeingWeatherHostAddress.setObjectName(u"seeingWeatherHostAddress")
        self.seeingWeatherHostAddress.setEnabled(True)
        self.seeingWeatherHostAddress.setGeometry(QRect(105, 40, 241, 21))
        self.seeingWeatherHostAddress.setMinimumSize(QSize(0, 0))
        self.seeingWeatherHostAddress.setFont(font1)
        self.seeingWeatherHostAddress.setMouseTracking(False)
        self.seeingWeatherHostAddress.setAcceptDrops(False)
        self.seeingWeatherHostAddress.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.seeingWeatherHostAddress.setMaxLength(50)
        self.seeingWeatherHostAddress.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.seeingWeatherHostAddress.setDragEnabled(True)
        self.seeingWeatherHostAddress.setReadOnly(False)
        self.label_mountIP_39 = QLabel(self.seeing)
        self.label_mountIP_39.setObjectName(u"label_mountIP_39")
        self.label_mountIP_39.setGeometry(QRect(15, 40, 81, 21))
        self.label_mountIP_39.setFont(font)
        self.seeingWeatherApiKey = QLineEdit(self.seeing)
        self.seeingWeatherApiKey.setObjectName(u"seeingWeatherApiKey")
        self.seeingWeatherApiKey.setGeometry(QRect(105, 70, 241, 21))
        self.seeingWeatherApiKey.setMinimumSize(QSize(0, 0))
        self.seeingWeatherApiKey.setFont(font1)
        self.seeingWeatherApiKey.setMouseTracking(False)
        self.seeingWeatherApiKey.setAcceptDrops(False)
        self.seeingWeatherApiKey.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.seeingWeatherApiKey.setMaxLength(50)
        self.seeingWeatherApiKey.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.seeingWeatherApiKey.setDragEnabled(True)
        self.seeingWeatherApiKey.setReadOnly(False)
        self.tab.addTab(self.seeing, "")
        self.relay = QWidget()
        self.relay.setObjectName(u"relay")
        self.label_mountIP_35 = QLabel(self.relay)
        self.label_mountIP_35.setObjectName(u"label_mountIP_35")
        self.label_mountIP_35.setGeometry(QRect(10, 40, 81, 21))
        self.label_mountIP_35.setFont(font)
        self.relayHostAddress = QLineEdit(self.relay)
        self.relayHostAddress.setObjectName(u"relayHostAddress")
        self.relayHostAddress.setEnabled(True)
        self.relayHostAddress.setGeometry(QRect(100, 40, 241, 21))
        self.relayHostAddress.setMinimumSize(QSize(0, 0))
        self.relayHostAddress.setFont(font1)
        self.relayHostAddress.setMouseTracking(False)
        self.relayHostAddress.setAcceptDrops(False)
        self.relayHostAddress.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.relayHostAddress.setMaxLength(50)
        self.relayHostAddress.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.relayHostAddress.setDragEnabled(True)
        self.relayHostAddress.setReadOnly(False)
        self.relayPassword = QLineEdit(self.relay)
        self.relayPassword.setObjectName(u"relayPassword")
        self.relayPassword.setGeometry(QRect(100, 100, 241, 21))
        self.relayPassword.setMinimumSize(QSize(0, 0))
        self.relayPassword.setFont(font1)
        self.relayPassword.setMouseTracking(False)
        self.relayPassword.setAcceptDrops(False)
        self.relayPassword.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.relayPassword.setMaxLength(50)
        self.relayPassword.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.relayPassword.setDragEnabled(True)
        self.relayPassword.setReadOnly(False)
        self.relayUser = QLineEdit(self.relay)
        self.relayUser.setObjectName(u"relayUser")
        self.relayUser.setGeometry(QRect(100, 70, 241, 21))
        self.relayUser.setMinimumSize(QSize(0, 0))
        self.relayUser.setFont(font1)
        self.relayUser.setMouseTracking(False)
        self.relayUser.setAcceptDrops(False)
        self.relayUser.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.relayUser.setMaxLength(50)
        self.relayUser.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.relayUser.setDragEnabled(True)
        self.relayUser.setReadOnly(False)
        self.label_mountIP_36 = QLabel(self.relay)
        self.label_mountIP_36.setObjectName(u"label_mountIP_36")
        self.label_mountIP_36.setGeometry(QRect(10, 70, 91, 21))
        self.label_mountIP_36.setFont(font)
        self.label_mountIP_37 = QLabel(self.relay)
        self.label_mountIP_37.setObjectName(u"label_mountIP_37")
        self.label_mountIP_37.setGeometry(QRect(10, 100, 91, 21))
        self.label_mountIP_37.setFont(font)
        self.tab.addTab(self.relay, "")
        self.ok = QPushButton(DevicePopup)
        self.ok.setObjectName(u"ok")
        self.ok.setGeometry(QRect(370, 270, 75, 21))
        self.cancel = QPushButton(DevicePopup)
        self.cancel.setObjectName(u"cancel")
        self.cancel.setGeometry(QRect(270, 270, 75, 21))
        self.iconPixmap = QLabel(DevicePopup)
        self.iconPixmap.setObjectName(u"iconPixmap")
        self.iconPixmap.setGeometry(QRect(10, 110, 64, 64))
        QWidget.setTabOrder(self.alpacaHostAddress, self.alpacaPort)
        QWidget.setTabOrder(self.alpacaPort, self.alpacaDeviceList)
        QWidget.setTabOrder(self.alpacaDeviceList, self.alpacaDiscover)
        QWidget.setTabOrder(self.alpacaDiscover, self.alpacaUser)
        QWidget.setTabOrder(self.alpacaUser, self.alpacaPassword)
        QWidget.setTabOrder(self.alpacaPassword, self.alpacaCopyConfig)
        QWidget.setTabOrder(self.alpacaCopyConfig, self.ascomDevice)
        QWidget.setTabOrder(self.ascomDevice, self.ascomSelector)
        QWidget.setTabOrder(self.ascomSelector, self.indiHostAddress)
        QWidget.setTabOrder(self.indiHostAddress, self.indiPort)
        QWidget.setTabOrder(self.indiPort, self.indiDeviceList)
        QWidget.setTabOrder(self.indiDeviceList, self.indiDiscover)
        QWidget.setTabOrder(self.indiDiscover, self.indiMessages)
        QWidget.setTabOrder(self.indiMessages, self.indiLoadConfig)
        QWidget.setTabOrder(self.indiLoadConfig, self.indiCopyConfig)
        QWidget.setTabOrder(self.indiCopyConfig, self.selectAstrometryAppPath)
        QWidget.setTabOrder(self.selectAstrometryAppPath, self.astrometryAppPath)
        QWidget.setTabOrder(self.astrometryAppPath, self.selectAstrometryIndexPath)
        QWidget.setTabOrder(self.selectAstrometryIndexPath, self.astrometryIndexPath)
        QWidget.setTabOrder(self.astrometryIndexPath, self.astrometryDeviceList)
        QWidget.setTabOrder(self.astrometryDeviceList, self.astrometrySearchRadius)
        QWidget.setTabOrder(self.astrometrySearchRadius, self.astrometryTimeout)
        QWidget.setTabOrder(self.astrometryTimeout, self.selectAstapAppPath)
        QWidget.setTabOrder(self.selectAstapAppPath, self.astapAppPath)
        QWidget.setTabOrder(self.astapAppPath, self.selectAstapIndexPath)
        QWidget.setTabOrder(self.selectAstapIndexPath, self.astapIndexPath)
        QWidget.setTabOrder(self.astapIndexPath, self.astapDeviceList)
        QWidget.setTabOrder(self.astapDeviceList, self.astapSearchRadius)
        QWidget.setTabOrder(self.astapSearchRadius, self.astapTimeout)
        QWidget.setTabOrder(self.astapTimeout, self.onlineWeatherHostAddress)
        QWidget.setTabOrder(self.onlineWeatherHostAddress, self.onlineWeatherApiKey)
        QWidget.setTabOrder(self.onlineWeatherApiKey, self.relayHostAddress)
        QWidget.setTabOrder(self.relayHostAddress, self.relayUser)
        QWidget.setTabOrder(self.relayUser, self.relayPassword)
        QWidget.setTabOrder(self.relayPassword, self.cancel)
        QWidget.setTabOrder(self.cancel, self.ok)
        QWidget.setTabOrder(self.ok, self.tab)

        self.retranslateUi(DevicePopup)

        self.tab.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(DevicePopup)
    # setupUi

    def retranslateUi(self, DevicePopup):
        DevicePopup.setWindowTitle(QCoreApplication.translate("DevicePopup", u"Device Setup", None))
        self.label_mountIP_7.setText(QCoreApplication.translate("DevicePopup", u"Device Name", None))
#if QT_CONFIG(tooltip)
        self.alpacaPort.setToolTip(QCoreApplication.translate("DevicePopup", u"Port of ALPACA server", None))
#endif // QT_CONFIG(tooltip)
        self.alpacaPort.setInputMask(QCoreApplication.translate("DevicePopup", u"00000", None))
        self.alpacaPort.setText(QCoreApplication.translate("DevicePopup", u"1", None))
        self.label_mountIP_8.setText(QCoreApplication.translate("DevicePopup", u"Host Address", None))
        self.label_mountIP_10.setText(QCoreApplication.translate("DevicePopup", u"Host Port", None))
#if QT_CONFIG(tooltip)
        self.alpacaHostAddress.setToolTip(QCoreApplication.translate("DevicePopup", u"<html><head/><body><p>IP address of INDI server, ip address and host names!</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.alpacaHostAddress.setText(QCoreApplication.translate("DevicePopup", u"localhost", None))
        self.label_mountIP_11.setText(QCoreApplication.translate("DevicePopup", u"User", None))
        self.label_mountIP_12.setText(QCoreApplication.translate("DevicePopup", u"Password", None))
#if QT_CONFIG(tooltip)
        self.alpacaUser.setToolTip(QCoreApplication.translate("DevicePopup", u"User for alpaca device", None))
#endif // QT_CONFIG(tooltip)
        self.alpacaUser.setText("")
#if QT_CONFIG(tooltip)
        self.alpacaPassword.setToolTip(QCoreApplication.translate("DevicePopup", u"Passwor for alpaca device", None))
#endif // QT_CONFIG(tooltip)
        self.alpacaPassword.setText("")
#if QT_CONFIG(tooltip)
        self.alpacaCopyConfig.setToolTip(QCoreApplication.translate("DevicePopup", u"<html><head/><body><p>Checked if you would like to enable blind solver function in SGPro</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.alpacaCopyConfig.setText(QCoreApplication.translate("DevicePopup", u"Copy config to all devices", None))
#if QT_CONFIG(tooltip)
        self.alpacaDiscover.setToolTip(QCoreApplication.translate("DevicePopup", u"<html><head/><body><p>Search collects a list of available ALPACA devices</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.alpacaDiscover.setText(QCoreApplication.translate("DevicePopup", u"Search", None))
        self.label_mountIP_22.setText(QCoreApplication.translate("DevicePopup", u"Poll", None))
        self.label_mountIP_23.setText(QCoreApplication.translate("DevicePopup", u"ms", None))
        self.tab.setTabText(self.tab.indexOf(self.alpaca), QCoreApplication.translate("DevicePopup", u"ALPACA", None))
#if QT_CONFIG(tooltip)
        self.ascomSelector.setToolTip(QCoreApplication.translate("DevicePopup", u"Starting the ASCOM device chooser.", None))
#endif // QT_CONFIG(tooltip)
        self.ascomSelector.setText(QCoreApplication.translate("DevicePopup", u"ASCOM device setup", None))
        self.label_mountIP_15.setText(QCoreApplication.translate("DevicePopup", u"Device Name", None))
#if QT_CONFIG(tooltip)
        self.ascomDevice.setToolTip(QCoreApplication.translate("DevicePopup", u"Drvice name of ASCOM driver.", None))
#endif // QT_CONFIG(tooltip)
        self.ascomDevice.setText("")
        self.tab.setTabText(self.tab.indexOf(self.ascom), QCoreApplication.translate("DevicePopup", u"ASCOM", None))
        self.label_mountIP_20.setText(QCoreApplication.translate("DevicePopup", u"Device Name", None))
        self.tab.setTabText(self.tab.indexOf(self.sgpro), QCoreApplication.translate("DevicePopup", u"SGPro", None))
        self.label_mountIP_21.setText(QCoreApplication.translate("DevicePopup", u"Device Name", None))
        self.tab.setTabText(self.tab.indexOf(self.nina), QCoreApplication.translate("DevicePopup", u"N.I.N.A.", None))
        self.label_mountIP_3.setText(QCoreApplication.translate("DevicePopup", u"Host Address", None))
#if QT_CONFIG(tooltip)
        self.indiHostAddress.setToolTip(QCoreApplication.translate("DevicePopup", u"IP address of INDI server, ip address and host names!", None))
#endif // QT_CONFIG(tooltip)
        self.indiHostAddress.setText(QCoreApplication.translate("DevicePopup", u"localhost", None))
        self.label_mountIP_4.setText(QCoreApplication.translate("DevicePopup", u"Host Port", None))
#if QT_CONFIG(tooltip)
        self.indiDiscover.setToolTip(QCoreApplication.translate("DevicePopup", u"<html><head/><body><p>Search collects a list of available INDI devices</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.indiDiscover.setText(QCoreApplication.translate("DevicePopup", u"Search", None))
        self.label_mountIP_5.setText(QCoreApplication.translate("DevicePopup", u"Device Name", None))
#if QT_CONFIG(tooltip)
        self.indiMessages.setToolTip(QCoreApplication.translate("DevicePopup", u"When checked, the indi messages received will be shown inthe central message window", None))
#endif // QT_CONFIG(tooltip)
        self.indiMessages.setText(QCoreApplication.translate("DevicePopup", u"Show Messages", None))
#if QT_CONFIG(tooltip)
        self.indiPort.setToolTip(QCoreApplication.translate("DevicePopup", u"Port of INDI server", None))
#endif // QT_CONFIG(tooltip)
        self.indiPort.setInputMask(QCoreApplication.translate("DevicePopup", u"00000", None))
        self.indiPort.setText(QCoreApplication.translate("DevicePopup", u"7", None))
#if QT_CONFIG(tooltip)
        self.indiLoadConfig.setToolTip(QCoreApplication.translate("DevicePopup", u"<html><head/><body><p>Checked if you would like to enable blind solver function in SGPro</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.indiLoadConfig.setText(QCoreApplication.translate("DevicePopup", u"Load configuration on start", None))
#if QT_CONFIG(tooltip)
        self.indiCopyConfig.setToolTip(QCoreApplication.translate("DevicePopup", u"<html><head/><body><p>Checked if you would like to enable blind solver function in SGPro</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.indiCopyConfig.setText(QCoreApplication.translate("DevicePopup", u"Copy config to all devices", None))
        self.label_mountIP_9.setText(QCoreApplication.translate("DevicePopup", u"Poll", None))
        self.label_mountIP_13.setText(QCoreApplication.translate("DevicePopup", u"ms", None))
        self.tab.setTabText(self.tab.indexOf(self.indi), QCoreApplication.translate("DevicePopup", u"INDI / INDIGO", None))
        self.label_mountIP_14.setText(QCoreApplication.translate("DevicePopup", u"Folder astrometry index", None))
#if QT_CONFIG(tooltip)
        self.astrometryIndexPath.setToolTip(QCoreApplication.translate("DevicePopup", u"<html><head/><body><p>Path to astrometry.net index files. Where native installation or e.g. KStars put the files.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.astrometryIndexPath.setText(QCoreApplication.translate("DevicePopup", u"/usr/", None))
#if QT_CONFIG(tooltip)
        self.selectAstrometryIndexPath.setToolTip(QCoreApplication.translate("DevicePopup", u"Select the directory of the astrometry.net index files", None))
#endif // QT_CONFIG(tooltip)
        self.selectAstrometryIndexPath.setText(QCoreApplication.translate("DevicePopup", u"Select", None))
#if QT_CONFIG(tooltip)
        self.astrometryDeviceList.setToolTip(QCoreApplication.translate("DevicePopup", u"Select the device.", None))
#endif // QT_CONFIG(tooltip)
        self.label_mountIP_6.setText(QCoreApplication.translate("DevicePopup", u"Device Name", None))
        self.label_316.setText(QCoreApplication.translate("DevicePopup", u"Timeout", None))
#if QT_CONFIG(tooltip)
        self.astrometrySearchRadius.setToolTip(QCoreApplication.translate("DevicePopup", u"Set the search radius for the plate solver. ", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.astrometryTimeout.setToolTip(QCoreApplication.translate("DevicePopup", u"Set the timeout for the plate solver.", None))
#endif // QT_CONFIG(tooltip)
        self.label_315.setText(QCoreApplication.translate("DevicePopup", u"Search radius", None))
        self.label_317.setText(QCoreApplication.translate("DevicePopup", u"s", None))
        self.label_318.setText(QCoreApplication.translate("DevicePopup", u"deg", None))
        self.label_mountIP_17.setText(QCoreApplication.translate("DevicePopup", u"Folder application", None))
#if QT_CONFIG(tooltip)
        self.astrometryAppPath.setToolTip(QCoreApplication.translate("DevicePopup", u"<html><head/><body><p>Path to astrometry.net binary files. Where native installation or e.g. KStars put the files.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.astrometryAppPath.setText(QCoreApplication.translate("DevicePopup", u"/usr/", None))
#if QT_CONFIG(tooltip)
        self.selectAstrometryAppPath.setToolTip(QCoreApplication.translate("DevicePopup", u"<html><head/><body><p>Select the directory of the astrometry.net application</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.selectAstrometryAppPath.setText(QCoreApplication.translate("DevicePopup", u"Select", None))
        self.tab.setTabText(self.tab.indexOf(self.astrometry), QCoreApplication.translate("DevicePopup", u"Astrometry", None))
        self.label_mountIP_16.setText(QCoreApplication.translate("DevicePopup", u"Device Name", None))
#if QT_CONFIG(tooltip)
        self.astapTimeout.setToolTip(QCoreApplication.translate("DevicePopup", u"Set the timeout for the plate solver.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.astapSearchRadius.setToolTip(QCoreApplication.translate("DevicePopup", u"Set the search radius for the plate solver. ", None))
#endif // QT_CONFIG(tooltip)
        self.label_319.setText(QCoreApplication.translate("DevicePopup", u"Timeout", None))
        self.label_320.setText(QCoreApplication.translate("DevicePopup", u"Search radius", None))
        self.label_321.setText(QCoreApplication.translate("DevicePopup", u"s", None))
        self.label_322.setText(QCoreApplication.translate("DevicePopup", u"deg  (use 180 to enable all sky)", None))
#if QT_CONFIG(tooltip)
        self.astapIndexPath.setToolTip(QCoreApplication.translate("DevicePopup", u"<html><head/><body><p>Path to astap index files.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.astapIndexPath.setText(QCoreApplication.translate("DevicePopup", u"/usr/", None))
#if QT_CONFIG(tooltip)
        self.astapAppPath.setToolTip(QCoreApplication.translate("DevicePopup", u"<html><head/><body><p>Path to astap application.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.astapAppPath.setText(QCoreApplication.translate("DevicePopup", u"/usr/", None))
#if QT_CONFIG(tooltip)
        self.selectAstapIndexPath.setToolTip(QCoreApplication.translate("DevicePopup", u"<html><head/><body><p>Select the directory of the astap index files</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.selectAstapIndexPath.setText(QCoreApplication.translate("DevicePopup", u"Select", None))
#if QT_CONFIG(tooltip)
        self.selectAstapAppPath.setToolTip(QCoreApplication.translate("DevicePopup", u"<html><head/><body><p>Select the directory of the astap application</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.selectAstapAppPath.setText(QCoreApplication.translate("DevicePopup", u"Select", None))
#if QT_CONFIG(tooltip)
        self.astapDeviceList.setToolTip(QCoreApplication.translate("DevicePopup", u"Select the device.", None))
#endif // QT_CONFIG(tooltip)
        self.label_mountIP_18.setText(QCoreApplication.translate("DevicePopup", u"Folder star index", None))
        self.label_mountIP_19.setText(QCoreApplication.translate("DevicePopup", u"Folder application", None))
        self.tab.setTabText(self.tab.indexOf(self.astap), QCoreApplication.translate("DevicePopup", u"ASTAP", None))
        self.label_323.setText(QCoreApplication.translate("DevicePopup", u"Search radius", None))
#if QT_CONFIG(tooltip)
        self.selectWatneyIndexPath.setToolTip(QCoreApplication.translate("DevicePopup", u"Select the directory of the astrometry.net index files", None))
#endif // QT_CONFIG(tooltip)
        self.selectWatneyIndexPath.setText(QCoreApplication.translate("DevicePopup", u"Select", None))
#if QT_CONFIG(tooltip)
        self.watneyTimeout.setToolTip(QCoreApplication.translate("DevicePopup", u"Set the timeout for the plate solver.", None))
#endif // QT_CONFIG(tooltip)
        self.label_324.setText(QCoreApplication.translate("DevicePopup", u"Timeout", None))
        self.label_mountIP_24.setText(QCoreApplication.translate("DevicePopup", u"Folder astrometry index", None))
#if QT_CONFIG(tooltip)
        self.watneyAppPath.setToolTip(QCoreApplication.translate("DevicePopup", u"<html><head/><body><p>Path to watney application.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.watneyAppPath.setText(QCoreApplication.translate("DevicePopup", u"/usr/", None))
        self.label_325.setText(QCoreApplication.translate("DevicePopup", u"deg  (use 180 to enable all sky)", None))
        self.label_326.setText(QCoreApplication.translate("DevicePopup", u"s", None))
#if QT_CONFIG(tooltip)
        self.watneySearchRadius.setToolTip(QCoreApplication.translate("DevicePopup", u"Set the search radius for the plate solver. ", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.watneyIndexPath.setToolTip(QCoreApplication.translate("DevicePopup", u"<html><head/><body><p>Path to watney star database.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.watneyIndexPath.setText(QCoreApplication.translate("DevicePopup", u"/usr/", None))
#if QT_CONFIG(tooltip)
        self.watneyDeviceList.setToolTip(QCoreApplication.translate("DevicePopup", u"Select the device.", None))
#endif // QT_CONFIG(tooltip)
        self.label_mountIP_25.setText(QCoreApplication.translate("DevicePopup", u"Device Name", None))
        self.label_mountIP_26.setText(QCoreApplication.translate("DevicePopup", u"Folder application", None))
#if QT_CONFIG(tooltip)
        self.selectWatneyAppPath.setToolTip(QCoreApplication.translate("DevicePopup", u"<html><head/><body><p>Select the directory of the watney application</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.selectWatneyAppPath.setText(QCoreApplication.translate("DevicePopup", u"Select", None))
        self.tab.setTabText(self.tab.indexOf(self.watney), QCoreApplication.translate("DevicePopup", u"Watney", None))
        self.label_mountIP_33.setText(QCoreApplication.translate("DevicePopup", u"Host Address", None))
#if QT_CONFIG(tooltip)
        self.onlineWeatherHostAddress.setToolTip(QCoreApplication.translate("DevicePopup", u"<html><head/><body><p>IP address for open weather service</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.onlineWeatherHostAddress.setText(QCoreApplication.translate("DevicePopup", u"api.openweathermap.org", None))
#if QT_CONFIG(tooltip)
        self.onlineWeatherApiKey.setToolTip(QCoreApplication.translate("DevicePopup", u"<html><head/><body><p>api key for open weather service</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.onlineWeatherApiKey.setText("")
        self.label_mountIP_34.setText(QCoreApplication.translate("DevicePopup", u"API Key", None))
        self.tab.setTabText(self.tab.indexOf(self.onlineWeather), QCoreApplication.translate("DevicePopup", u"Online Weather", None))
        self.label_mountIP_38.setText(QCoreApplication.translate("DevicePopup", u"API Key", None))
#if QT_CONFIG(tooltip)
        self.seeingWeatherHostAddress.setToolTip(QCoreApplication.translate("DevicePopup", u"<html><head/><body><p>IP address for open weather service</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.seeingWeatherHostAddress.setText(QCoreApplication.translate("DevicePopup", u"api.openweathermap.org", None))
        self.label_mountIP_39.setText(QCoreApplication.translate("DevicePopup", u"Host Address", None))
#if QT_CONFIG(tooltip)
        self.seeingWeatherApiKey.setToolTip(QCoreApplication.translate("DevicePopup", u"<html><head/><body><p>api key for open weather service</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.seeingWeatherApiKey.setText("")
        self.tab.setTabText(self.tab.indexOf(self.seeing), QCoreApplication.translate("DevicePopup", u"Seeing Weather", None))
        self.label_mountIP_35.setText(QCoreApplication.translate("DevicePopup", u"Host Address", None))
#if QT_CONFIG(tooltip)
        self.relayHostAddress.setToolTip(QCoreApplication.translate("DevicePopup", u"<html><head/><body><p>IP address for relay device</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.relayHostAddress.setText("")
#if QT_CONFIG(tooltip)
        self.relayPassword.setToolTip(QCoreApplication.translate("DevicePopup", u"<html><head/><body><p>Passwor for relay device</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.relayPassword.setText("")
#if QT_CONFIG(tooltip)
        self.relayUser.setToolTip(QCoreApplication.translate("DevicePopup", u"<html><head/><body><p>User for relay device</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.relayUser.setText("")
        self.label_mountIP_36.setText(QCoreApplication.translate("DevicePopup", u"User", None))
        self.label_mountIP_37.setText(QCoreApplication.translate("DevicePopup", u"Password", None))
        self.tab.setTabText(self.tab.indexOf(self.relay), QCoreApplication.translate("DevicePopup", u"Relay", None))
        self.ok.setText(QCoreApplication.translate("DevicePopup", u"OK", None))
        self.cancel.setText(QCoreApplication.translate("DevicePopup", u"Cancel", None))
        self.iconPixmap.setText(QCoreApplication.translate("DevicePopup", u"TextLabel", None))
    # retranslateUi

