# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'keypad.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QWidget)

class Ui_KeypadDialog(object):
    def setupUi(self, KeypadDialog):
        if not KeypadDialog.objectName():
            KeypadDialog.setObjectName(u"KeypadDialog")
        KeypadDialog.resize(270, 600)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(KeypadDialog.sizePolicy().hasHeightForWidth())
        KeypadDialog.setSizePolicy(sizePolicy)
        KeypadDialog.setMinimumSize(QSize(270, 600))
        KeypadDialog.setMaximumSize(QSize(270, 600))
        KeypadDialog.setSizeIncrement(QSize(10, 10))
        KeypadDialog.setBaseSize(QSize(10, 10))
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(10)
        KeypadDialog.setFont(font)
        self.b2 = QPushButton(KeypadDialog)
        self.b2.setObjectName(u"b2")
        self.b2.setGeometry(QRect(80, 475, 50, 50))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.b2.sizePolicy().hasHeightForWidth())
        self.b2.setSizePolicy(sizePolicy1)
        self.b2.setMinimumSize(QSize(50, 50))
        self.b2.setMaximumSize(QSize(50, 50))
        font1 = QFont()
        font1.setFamilies([u"Arial"])
        font1.setPointSize(8)
        self.b2.setFont(font1)
        self.b2.setProperty(u"keypad", True)
        self.bdown = QPushButton(KeypadDialog)
        self.bdown.setObjectName(u"bdown")
        self.bdown.setGeometry(QRect(110, 295, 50, 50))
        sizePolicy.setHeightForWidth(self.bdown.sizePolicy().hasHeightForWidth())
        self.bdown.setSizePolicy(sizePolicy)
        self.bdown.setMinimumSize(QSize(50, 50))
        self.bdown.setMaximumSize(QSize(50, 50))
        self.bdown.setFont(font1)
        self.bdown.setProperty(u"keypad", True)
        self.bminus = QPushButton(KeypadDialog)
        self.bminus.setObjectName(u"bminus")
        self.bminus.setGeometry(QRect(200, 415, 50, 50))
        sizePolicy1.setHeightForWidth(self.bminus.sizePolicy().hasHeightForWidth())
        self.bminus.setSizePolicy(sizePolicy1)
        self.bminus.setMinimumSize(QSize(50, 50))
        self.bminus.setMaximumSize(QSize(50, 50))
        self.bminus.setFont(font1)
        self.bminus.setProperty(u"keypad", False)
        self.b4 = QPushButton(KeypadDialog)
        self.b4.setObjectName(u"b4")
        self.b4.setGeometry(QRect(20, 415, 50, 50))
        sizePolicy1.setHeightForWidth(self.b4.sizePolicy().hasHeightForWidth())
        self.b4.setSizePolicy(sizePolicy1)
        self.b4.setMinimumSize(QSize(50, 50))
        self.b4.setMaximumSize(QSize(50, 50))
        self.b4.setFont(font1)
        self.b4.setProperty(u"keypad", True)
        self.besc = QPushButton(KeypadDialog)
        self.besc.setObjectName(u"besc")
        self.besc.setGeometry(QRect(80, 535, 50, 50))
        sizePolicy1.setHeightForWidth(self.besc.sizePolicy().hasHeightForWidth())
        self.besc.setSizePolicy(sizePolicy1)
        self.besc.setMinimumSize(QSize(50, 50))
        self.besc.setMaximumSize(QSize(50, 50))
        self.besc.setFont(font1)
        self.besc.setProperty(u"keypad", True)
        self.b0 = QPushButton(KeypadDialog)
        self.b0.setObjectName(u"b0")
        self.b0.setGeometry(QRect(20, 535, 50, 50))
        sizePolicy1.setHeightForWidth(self.b0.sizePolicy().hasHeightForWidth())
        self.b0.setSizePolicy(sizePolicy1)
        self.b0.setMinimumSize(QSize(50, 50))
        self.b0.setMaximumSize(QSize(50, 50))
        self.b0.setFont(font1)
        self.b0.setProperty(u"keypad", True)
        self.bmenu = QPushButton(KeypadDialog)
        self.bmenu.setObjectName(u"bmenu")
        self.bmenu.setGeometry(QRect(140, 535, 50, 50))
        sizePolicy1.setHeightForWidth(self.bmenu.sizePolicy().hasHeightForWidth())
        self.bmenu.setSizePolicy(sizePolicy1)
        self.bmenu.setMinimumSize(QSize(50, 50))
        self.bmenu.setMaximumSize(QSize(50, 50))
        self.bmenu.setFont(font1)
        self.bmenu.setProperty(u"keypad", True)
        self.b7 = QPushButton(KeypadDialog)
        self.b7.setObjectName(u"b7")
        self.b7.setGeometry(QRect(20, 355, 50, 50))
        sizePolicy1.setHeightForWidth(self.b7.sizePolicy().hasHeightForWidth())
        self.b7.setSizePolicy(sizePolicy1)
        self.b7.setMinimumSize(QSize(50, 50))
        self.b7.setMaximumSize(QSize(50, 50))
        self.b7.setFont(font1)
        self.b7.setProperty(u"keypad", True)
        self.benter = QPushButton(KeypadDialog)
        self.benter.setObjectName(u"benter")
        self.benter.setGeometry(QRect(200, 475, 50, 50))
        sizePolicy1.setHeightForWidth(self.benter.sizePolicy().hasHeightForWidth())
        self.benter.setSizePolicy(sizePolicy1)
        self.benter.setMinimumSize(QSize(50, 50))
        self.benter.setMaximumSize(QSize(50, 50))
        self.benter.setFont(font1)
        self.benter.setProperty(u"keypad", True)
        self.b3 = QPushButton(KeypadDialog)
        self.b3.setObjectName(u"b3")
        self.b3.setGeometry(QRect(140, 475, 50, 50))
        sizePolicy1.setHeightForWidth(self.b3.sizePolicy().hasHeightForWidth())
        self.b3.setSizePolicy(sizePolicy1)
        self.b3.setMinimumSize(QSize(50, 50))
        self.b3.setMaximumSize(QSize(50, 50))
        self.b3.setFont(font1)
        self.b3.setProperty(u"keypad", True)
        self.bright = QPushButton(KeypadDialog)
        self.bright.setObjectName(u"bright")
        self.bright.setGeometry(QRect(170, 265, 50, 50))
        sizePolicy1.setHeightForWidth(self.bright.sizePolicy().hasHeightForWidth())
        self.bright.setSizePolicy(sizePolicy1)
        self.bright.setMinimumSize(QSize(50, 50))
        self.bright.setMaximumSize(QSize(50, 50))
        self.bright.setFont(font1)
        self.bright.setProperty(u"keypad", True)
        self.b1 = QPushButton(KeypadDialog)
        self.b1.setObjectName(u"b1")
        self.b1.setGeometry(QRect(20, 475, 50, 50))
        sizePolicy1.setHeightForWidth(self.b1.sizePolicy().hasHeightForWidth())
        self.b1.setSizePolicy(sizePolicy1)
        self.b1.setMinimumSize(QSize(50, 50))
        self.b1.setMaximumSize(QSize(50, 50))
        self.b1.setFont(font1)
        self.b1.setProperty(u"keypad", True)
        self.bup = QPushButton(KeypadDialog)
        self.bup.setObjectName(u"bup")
        self.bup.setGeometry(QRect(110, 230, 50, 50))
        sizePolicy.setHeightForWidth(self.bup.sizePolicy().hasHeightForWidth())
        self.bup.setSizePolicy(sizePolicy)
        self.bup.setMinimumSize(QSize(50, 50))
        self.bup.setMaximumSize(QSize(50, 50))
        self.bup.setFont(font1)
        self.bup.setProperty(u"keypad", True)
        self.b8 = QPushButton(KeypadDialog)
        self.b8.setObjectName(u"b8")
        self.b8.setGeometry(QRect(80, 355, 50, 50))
        sizePolicy1.setHeightForWidth(self.b8.sizePolicy().hasHeightForWidth())
        self.b8.setSizePolicy(sizePolicy1)
        self.b8.setMinimumSize(QSize(50, 50))
        self.b8.setMaximumSize(QSize(50, 50))
        self.b8.setFont(font1)
        self.b8.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.b8.setProperty(u"keypad", True)
        self.bstop = QPushButton(KeypadDialog)
        self.bstop.setObjectName(u"bstop")
        self.bstop.setGeometry(QRect(200, 535, 50, 50))
        sizePolicy1.setHeightForWidth(self.bstop.sizePolicy().hasHeightForWidth())
        self.bstop.setSizePolicy(sizePolicy1)
        self.bstop.setMinimumSize(QSize(50, 50))
        self.bstop.setMaximumSize(QSize(50, 50))
        self.bstop.setFont(font1)
        self.bstop.setProperty(u"keypad", True)
        self.b6 = QPushButton(KeypadDialog)
        self.b6.setObjectName(u"b6")
        self.b6.setGeometry(QRect(140, 415, 50, 50))
        sizePolicy1.setHeightForWidth(self.b6.sizePolicy().hasHeightForWidth())
        self.b6.setSizePolicy(sizePolicy1)
        self.b6.setMinimumSize(QSize(50, 50))
        self.b6.setMaximumSize(QSize(50, 50))
        self.b6.setFont(font1)
        self.b6.setProperty(u"keypad", True)
        self.b9 = QPushButton(KeypadDialog)
        self.b9.setObjectName(u"b9")
        self.b9.setGeometry(QRect(140, 355, 50, 50))
        sizePolicy1.setHeightForWidth(self.b9.sizePolicy().hasHeightForWidth())
        self.b9.setSizePolicy(sizePolicy1)
        self.b9.setMinimumSize(QSize(50, 50))
        self.b9.setMaximumSize(QSize(50, 50))
        self.b9.setFont(font1)
        self.b9.setProperty(u"keypad", True)
        self.graphics = QLabel(KeypadDialog)
        self.graphics.setObjectName(u"graphics")
        self.graphics.setGeometry(QRect(10, 75, 256, 128))
        self.graphics.setMinimumSize(QSize(0, 20))
        self.bplus = QPushButton(KeypadDialog)
        self.bplus.setObjectName(u"bplus")
        self.bplus.setGeometry(QRect(200, 355, 50, 50))
        sizePolicy1.setHeightForWidth(self.bplus.sizePolicy().hasHeightForWidth())
        self.bplus.setSizePolicy(sizePolicy1)
        self.bplus.setMinimumSize(QSize(50, 50))
        self.bplus.setMaximumSize(QSize(50, 50))
        self.bplus.setFont(font1)
        self.bplus.setProperty(u"keypad", True)
        self.bleft = QPushButton(KeypadDialog)
        self.bleft.setObjectName(u"bleft")
        self.bleft.setGeometry(QRect(50, 265, 50, 50))
        sizePolicy1.setHeightForWidth(self.bleft.sizePolicy().hasHeightForWidth())
        self.bleft.setSizePolicy(sizePolicy1)
        self.bleft.setMinimumSize(QSize(50, 50))
        self.bleft.setMaximumSize(QSize(50, 50))
        self.bleft.setFont(font1)
        self.bleft.setProperty(u"keypad", True)
        self.b5 = QPushButton(KeypadDialog)
        self.b5.setObjectName(u"b5")
        self.b5.setGeometry(QRect(80, 415, 50, 50))
        sizePolicy1.setHeightForWidth(self.b5.sizePolicy().hasHeightForWidth())
        self.b5.setSizePolicy(sizePolicy1)
        self.b5.setMinimumSize(QSize(50, 50))
        self.b5.setMaximumSize(QSize(50, 50))
        self.b5.setFont(font1)
        self.b5.setProperty(u"keypad", True)
        self.row0 = QLineEdit(KeypadDialog)
        self.row0.setObjectName(u"row0")
        self.row0.setGeometry(QRect(10, 15, 256, 25))
        self.row0.setFrame(False)
        self.row0.setReadOnly(True)
        self.row0.setProperty(u"keypad", True)
        self.row1 = QLineEdit(KeypadDialog)
        self.row1.setObjectName(u"row1")
        self.row1.setGeometry(QRect(10, 45, 256, 25))
        self.row1.setFrame(False)
        self.row1.setReadOnly(True)
        self.row1.setProperty(u"keypad", True)
        self.row2 = QLineEdit(KeypadDialog)
        self.row2.setObjectName(u"row2")
        self.row2.setGeometry(QRect(10, 75, 256, 25))
        self.row2.setFrame(False)
        self.row2.setReadOnly(True)
        self.row2.setProperty(u"keypad", True)
        self.row3 = QLineEdit(KeypadDialog)
        self.row3.setObjectName(u"row3")
        self.row3.setGeometry(QRect(10, 105, 256, 25))
        self.row3.setFrame(False)
        self.row3.setReadOnly(True)
        self.row3.setProperty(u"keypad", True)
        self.row4 = QLineEdit(KeypadDialog)
        self.row4.setObjectName(u"row4")
        self.row4.setGeometry(QRect(10, 135, 256, 25))
        self.row4.setFrame(False)
        self.row4.setReadOnly(True)
        self.row4.setProperty(u"keypad", True)
        self.label = QLabel(KeypadDialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 220, 251, 376))
        self.label.setProperty(u"keypad", True)
        self.cursor = QFrame(KeypadDialog)
        self.cursor.setObjectName(u"cursor")
        self.cursor.setGeometry(QRect(10, 220, 15, 3))
        self.cursor.setFrameShadow(QFrame.Shadow.Plain)
        self.cursor.setLineWidth(3)
        self.cursor.setMidLineWidth(0)
        self.cursor.setFrameShape(QFrame.Shape.HLine)
        self.label.raise_()
        self.graphics.raise_()
        self.b2.raise_()
        self.bdown.raise_()
        self.bminus.raise_()
        self.b4.raise_()
        self.besc.raise_()
        self.b0.raise_()
        self.bmenu.raise_()
        self.b7.raise_()
        self.benter.raise_()
        self.b3.raise_()
        self.bright.raise_()
        self.b1.raise_()
        self.bup.raise_()
        self.b8.raise_()
        self.bstop.raise_()
        self.b6.raise_()
        self.b9.raise_()
        self.bplus.raise_()
        self.bleft.raise_()
        self.b5.raise_()
        self.row0.raise_()
        self.row1.raise_()
        self.row2.raise_()
        self.row3.raise_()
        self.row4.raise_()
        self.cursor.raise_()

        self.retranslateUi(KeypadDialog)

        QMetaObject.connectSlotsByName(KeypadDialog)
    # setupUi

    def retranslateUi(self, KeypadDialog):
        KeypadDialog.setWindowTitle(QCoreApplication.translate("KeypadDialog", u"Virtual Keypad", None))
        self.b2.setText(QCoreApplication.translate("KeypadDialog", u"2\n"
"INFO", None))
        self.bdown.setText(QCoreApplication.translate("KeypadDialog", u"S", None))
        self.bminus.setText(QCoreApplication.translate("KeypadDialog", u"-\n"
"DOWN", None))
        self.b4.setText(QCoreApplication.translate("KeypadDialog", u"4\n"
"STAR", None))
        self.besc.setText(QCoreApplication.translate("KeypadDialog", u"ESC", None))
        self.b0.setText(QCoreApplication.translate("KeypadDialog", u"0\n"
"LIGHT", None))
        self.bmenu.setText(QCoreApplication.translate("KeypadDialog", u"MENU", None))
        self.b7.setText(QCoreApplication.translate("KeypadDialog", u"7\n"
"M", None))
        self.benter.setText(QCoreApplication.translate("KeypadDialog", u"ENTER", None))
        self.b3.setText(QCoreApplication.translate("KeypadDialog", u"3\n"
"DISP", None))
        self.bright.setText(QCoreApplication.translate("KeypadDialog", u"W", None))
        self.b1.setText(QCoreApplication.translate("KeypadDialog", u"1\n"
"COORD", None))
        self.bup.setText(QCoreApplication.translate("KeypadDialog", u"N", None))
        self.b8.setText(QCoreApplication.translate("KeypadDialog", u"8\n"
"NGC", None))
        self.bstop.setText(QCoreApplication.translate("KeypadDialog", u"STOP", None))
        self.b6.setText(QCoreApplication.translate("KeypadDialog", u"6\n"
"MORE", None))
        self.b9.setText(QCoreApplication.translate("KeypadDialog", u"9\n"
"IC", None))
        self.graphics.setText("")
        self.bplus.setText(QCoreApplication.translate("KeypadDialog", u"+\n"
"UP", None))
        self.bleft.setText(QCoreApplication.translate("KeypadDialog", u"E", None))
        self.b5.setText(QCoreApplication.translate("KeypadDialog", u"5\n"
"PLANET", None))
        self.label.setText("")
    # retranslateUi

