# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'material.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QSizePolicy,
    QSlider, QTabWidget, QVBoxLayout, QWidget)

class Ui_MaterialDialog(object):
    def setupUi(self, MaterialDialog):
        if not MaterialDialog.objectName():
            MaterialDialog.setObjectName(u"MaterialDialog")
        MaterialDialog.resize(800, 600)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MaterialDialog.sizePolicy().hasHeightForWidth())
        MaterialDialog.setSizePolicy(sizePolicy)
        MaterialDialog.setMinimumSize(QSize(800, 285))
        MaterialDialog.setMaximumSize(QSize(800, 1200))
        MaterialDialog.setSizeIncrement(QSize(10, 10))
        MaterialDialog.setBaseSize(QSize(10, 10))
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(10)
        MaterialDialog.setFont(font)
        self.verticalLayout = QVBoxLayout(MaterialDialog)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.tabWidget = QTabWidget(MaterialDialog)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.mtg2 = QLineEdit(self.tab)
        self.mtg2.setObjectName(u"mtg2")
        self.mtg2.setGeometry(QRect(680, 300, 81, 25))
        self.mtr2 = QLineEdit(self.tab)
        self.mtr2.setObjectName(u"mtr2")
        self.mtr2.setGeometry(QRect(680, 270, 81, 25))
        self.mg2 = QSlider(self.tab)
        self.mg2.setObjectName(u"mg2")
        self.mg2.setGeometry(QRect(115, 300, 550, 25))
        self.mg2.setMaximum(255)
        self.mg2.setPageStep(1)
        self.mg2.setOrientation(Qt.Horizontal)
        self.lg2 = QLabel(self.tab)
        self.lg2.setObjectName(u"lg2")
        self.lg2.setGeometry(QRect(30, 300, 81, 25))
        self.mr2 = QSlider(self.tab)
        self.mr2.setObjectName(u"mr2")
        self.mr2.setGeometry(QRect(115, 270, 550, 25))
        self.mr2.setMaximum(255)
        self.mr2.setPageStep(1)
        self.mr2.setOrientation(Qt.Horizontal)
        self.mtb2 = QLineEdit(self.tab)
        self.mtb2.setObjectName(u"mtb2")
        self.mtb2.setGeometry(QRect(680, 330, 81, 25))
        self.lb2 = QLabel(self.tab)
        self.lb2.setObjectName(u"lb2")
        self.lb2.setGeometry(QRect(30, 330, 81, 25))
        self.mb2 = QSlider(self.tab)
        self.mb2.setObjectName(u"mb2")
        self.mb2.setGeometry(QRect(115, 330, 550, 25))
        self.mb2.setMaximum(255)
        self.mb2.setPageStep(1)
        self.mb2.setOrientation(Qt.Horizontal)
        self.lr2 = QLabel(self.tab)
        self.lr2.setObjectName(u"lr2")
        self.lr2.setGeometry(QRect(30, 270, 81, 25))
        self.lb0 = QLabel(self.tab)
        self.lb0.setObjectName(u"lb0")
        self.lb0.setGeometry(QRect(30, 95, 81, 25))
        self.mtb0 = QLineEdit(self.tab)
        self.mtb0.setObjectName(u"mtb0")
        self.mtb0.setGeometry(QRect(680, 95, 81, 25))
        self.mb0 = QSlider(self.tab)
        self.mb0.setObjectName(u"mb0")
        self.mb0.setGeometry(QRect(115, 95, 550, 25))
        self.mb0.setMaximum(255)
        self.mb0.setPageStep(1)
        self.mb0.setOrientation(Qt.Horizontal)
        self.mtg0 = QLineEdit(self.tab)
        self.mtg0.setObjectName(u"mtg0")
        self.mtg0.setGeometry(QRect(680, 65, 81, 25))
        self.mtr0 = QLineEdit(self.tab)
        self.mtr0.setObjectName(u"mtr0")
        self.mtr0.setGeometry(QRect(680, 35, 81, 25))
        self.l0 = QLabel(self.tab)
        self.l0.setObjectName(u"l0")
        self.l0.setGeometry(QRect(30, 380, 81, 25))
        self.lr0 = QLabel(self.tab)
        self.lr0.setObjectName(u"lr0")
        self.lr0.setGeometry(QRect(30, 35, 81, 25))
        self.mr0 = QSlider(self.tab)
        self.mr0.setObjectName(u"mr0")
        self.mr0.setGeometry(QRect(115, 35, 550, 25))
        self.mr0.setMaximum(255)
        self.mr0.setPageStep(1)
        self.mr0.setOrientation(Qt.Horizontal)
        self.ms0 = QSlider(self.tab)
        self.ms0.setObjectName(u"ms0")
        self.ms0.setGeometry(QRect(115, 380, 550, 25))
        self.ms0.setMaximum(1000)
        self.ms0.setPageStep(1)
        self.ms0.setOrientation(Qt.Horizontal)
        self.mt0 = QLineEdit(self.tab)
        self.mt0.setObjectName(u"mt0")
        self.mt0.setGeometry(QRect(680, 380, 81, 25))
        self.lg0 = QLabel(self.tab)
        self.lg0.setObjectName(u"lg0")
        self.lg0.setGeometry(QRect(30, 65, 81, 25))
        self.mg0 = QSlider(self.tab)
        self.mg0.setObjectName(u"mg0")
        self.mg0.setGeometry(QRect(115, 65, 550, 25))
        self.mg0.setMaximum(255)
        self.mg0.setPageStep(1)
        self.mg0.setTracking(True)
        self.mg0.setOrientation(Qt.Horizontal)
        self.mg0.setTickPosition(QSlider.NoTicks)
        self.mg0.setTickInterval(0)
        self.name = QLineEdit(self.tab)
        self.name.setObjectName(u"name")
        self.name.setGeometry(QRect(25, 460, 221, 21))
        self.material = QLineEdit(self.tab)
        self.material.setObjectName(u"material")
        self.material.setGeometry(QRect(25, 500, 221, 21))
        self.lg1 = QLabel(self.tab)
        self.lg1.setObjectName(u"lg1")
        self.lg1.setGeometry(QRect(30, 180, 81, 25))
        self.lr1 = QLabel(self.tab)
        self.lr1.setObjectName(u"lr1")
        self.lr1.setGeometry(QRect(30, 150, 81, 25))
        self.mg1 = QSlider(self.tab)
        self.mg1.setObjectName(u"mg1")
        self.mg1.setGeometry(QRect(115, 180, 550, 25))
        self.mg1.setMaximum(255)
        self.mg1.setPageStep(1)
        self.mg1.setOrientation(Qt.Horizontal)
        self.mtr1 = QLineEdit(self.tab)
        self.mtr1.setObjectName(u"mtr1")
        self.mtr1.setGeometry(QRect(680, 150, 81, 25))
        self.mtb1 = QLineEdit(self.tab)
        self.mtb1.setObjectName(u"mtb1")
        self.mtb1.setGeometry(QRect(680, 210, 81, 25))
        self.mr1 = QSlider(self.tab)
        self.mr1.setObjectName(u"mr1")
        self.mr1.setGeometry(QRect(115, 150, 550, 25))
        self.mr1.setMaximum(255)
        self.mr1.setPageStep(1)
        self.mr1.setOrientation(Qt.Horizontal)
        self.lb1 = QLabel(self.tab)
        self.lb1.setObjectName(u"lb1")
        self.lb1.setGeometry(QRect(30, 210, 81, 25))
        self.mb1 = QSlider(self.tab)
        self.mb1.setObjectName(u"mb1")
        self.mb1.setGeometry(QRect(115, 210, 550, 25))
        self.mb1.setMaximum(255)
        self.mb1.setPageStep(1)
        self.mb1.setOrientation(Qt.Horizontal)
        self.mtg1 = QLineEdit(self.tab)
        self.mtg1.setObjectName(u"mtg1")
        self.mtg1.setGeometry(QRect(680, 180, 81, 25))
        self.l1 = QLabel(self.tab)
        self.l1.setObjectName(u"l1")
        self.l1.setGeometry(QRect(30, 410, 81, 25))
        self.mt1 = QLineEdit(self.tab)
        self.mt1.setObjectName(u"mt1")
        self.mt1.setGeometry(QRect(680, 410, 81, 25))
        self.ms1 = QSlider(self.tab)
        self.ms1.setObjectName(u"ms1")
        self.ms1.setGeometry(QRect(115, 410, 550, 25))
        self.ms1.setMaximum(1000)
        self.ms1.setPageStep(1)
        self.ms1.setOrientation(Qt.Horizontal)
        self.tabWidget.addTab(self.tab, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.t4_b_3 = QLineEdit(self.tab_7)
        self.t4_b_3.setObjectName(u"t4_b_3")
        self.t4_b_3.setGeometry(QRect(680, 275, 81, 25))
        self.t4_s2_3 = QSlider(self.tab_7)
        self.t4_s2_3.setObjectName(u"t4_s2_3")
        self.t4_s2_3.setGeometry(QRect(115, 95, 550, 25))
        self.t4_s2_3.setMaximum(1000)
        self.t4_s2_3.setPageStep(1)
        self.t4_s2_3.setOrientation(Qt.Horizontal)
        self.label_15 = QLabel(self.tab_7)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(30, 95, 81, 25))
        self.t4_sb_3 = QSlider(self.tab_7)
        self.t4_sb_3.setObjectName(u"t4_sb_3")
        self.t4_sb_3.setGeometry(QRect(115, 275, 550, 25))
        self.t4_sb_3.setMaximum(255)
        self.t4_sb_3.setPageStep(1)
        self.t4_sb_3.setOrientation(Qt.Horizontal)
        self.t4_8 = QLineEdit(self.tab_7)
        self.t4_8.setObjectName(u"t4_8")
        self.t4_8.setGeometry(QRect(680, 130, 81, 25))
        self.t4_r_3 = QLineEdit(self.tab_7)
        self.t4_r_3.setObjectName(u"t4_r_3")
        self.t4_r_3.setGeometry(QRect(680, 205, 81, 25))
        self.t4_s3_3 = QSlider(self.tab_7)
        self.t4_s3_3.setObjectName(u"t4_s3_3")
        self.t4_s3_3.setGeometry(QRect(115, 130, 550, 25))
        self.t4_s3_3.setMaximum(1000)
        self.t4_s3_3.setPageStep(1)
        self.t4_s3_3.setOrientation(Qt.Horizontal)
        self.t4_sg_3 = QSlider(self.tab_7)
        self.t4_sg_3.setObjectName(u"t4_sg_3")
        self.t4_sg_3.setGeometry(QRect(115, 240, 550, 25))
        self.t4_sg_3.setMaximum(255)
        self.t4_sg_3.setPageStep(1)
        self.t4_sg_3.setOrientation(Qt.Horizontal)
        self.label_16 = QLabel(self.tab_7)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(30, 60, 81, 25))
        self.t4_s1_3 = QSlider(self.tab_7)
        self.t4_s1_3.setObjectName(u"t4_s1_3")
        self.t4_s1_3.setGeometry(QRect(115, 60, 550, 25))
        self.t4_s1_3.setMaximum(1000)
        self.t4_s1_3.setPageStep(1)
        self.t4_s1_3.setTracking(True)
        self.t4_s1_3.setOrientation(Qt.Horizontal)
        self.t4_s1_3.setTickPosition(QSlider.NoTicks)
        self.t4_s1_3.setTickInterval(0)
        self.label_17 = QLabel(self.tab_7)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(30, 25, 81, 25))
        self.t4_9 = QLineEdit(self.tab_7)
        self.t4_9.setObjectName(u"t4_9")
        self.t4_9.setGeometry(QRect(680, 25, 81, 25))
        self.label_18 = QLabel(self.tab_7)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(30, 205, 81, 25))
        self.t4_10 = QLineEdit(self.tab_7)
        self.t4_10.setObjectName(u"t4_10")
        self.t4_10.setGeometry(QRect(680, 95, 81, 25))
        self.t4_s0_3 = QSlider(self.tab_7)
        self.t4_s0_3.setObjectName(u"t4_s0_3")
        self.t4_s0_3.setGeometry(QRect(115, 25, 550, 25))
        self.t4_s0_3.setMaximum(100)
        self.t4_s0_3.setPageStep(1)
        self.t4_s0_3.setOrientation(Qt.Horizontal)
        self.t4_sr_3 = QSlider(self.tab_7)
        self.t4_sr_3.setObjectName(u"t4_sr_3")
        self.t4_sr_3.setGeometry(QRect(115, 205, 550, 25))
        self.t4_sr_3.setMaximum(255)
        self.t4_sr_3.setPageStep(1)
        self.t4_sr_3.setOrientation(Qt.Horizontal)
        self.label_19 = QLabel(self.tab_7)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(30, 275, 81, 25))
        self.label_20 = QLabel(self.tab_7)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(30, 130, 81, 25))
        self.label_21 = QLabel(self.tab_7)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(30, 240, 81, 25))
        self.t4_g_3 = QLineEdit(self.tab_7)
        self.t4_g_3.setObjectName(u"t4_g_3")
        self.t4_g_3.setGeometry(QRect(680, 240, 81, 25))
        self.t4_11 = QLineEdit(self.tab_7)
        self.t4_11.setObjectName(u"t4_11")
        self.t4_11.setGeometry(QRect(680, 60, 81, 25))
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.t4_b_4 = QLineEdit(self.tab_6)
        self.t4_b_4.setObjectName(u"t4_b_4")
        self.t4_b_4.setGeometry(QRect(680, 275, 81, 25))
        self.t4_s2_4 = QSlider(self.tab_6)
        self.t4_s2_4.setObjectName(u"t4_s2_4")
        self.t4_s2_4.setGeometry(QRect(115, 95, 550, 25))
        self.t4_s2_4.setMaximum(1000)
        self.t4_s2_4.setPageStep(1)
        self.t4_s2_4.setOrientation(Qt.Horizontal)
        self.label_22 = QLabel(self.tab_6)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(30, 95, 81, 25))
        self.t4_sb_4 = QSlider(self.tab_6)
        self.t4_sb_4.setObjectName(u"t4_sb_4")
        self.t4_sb_4.setGeometry(QRect(115, 275, 550, 25))
        self.t4_sb_4.setMaximum(255)
        self.t4_sb_4.setPageStep(1)
        self.t4_sb_4.setOrientation(Qt.Horizontal)
        self.t4_12 = QLineEdit(self.tab_6)
        self.t4_12.setObjectName(u"t4_12")
        self.t4_12.setGeometry(QRect(680, 130, 81, 25))
        self.t4_r_4 = QLineEdit(self.tab_6)
        self.t4_r_4.setObjectName(u"t4_r_4")
        self.t4_r_4.setGeometry(QRect(680, 205, 81, 25))
        self.t4_s3_4 = QSlider(self.tab_6)
        self.t4_s3_4.setObjectName(u"t4_s3_4")
        self.t4_s3_4.setGeometry(QRect(115, 130, 550, 25))
        self.t4_s3_4.setMaximum(1000)
        self.t4_s3_4.setPageStep(1)
        self.t4_s3_4.setOrientation(Qt.Horizontal)
        self.t4_sg_4 = QSlider(self.tab_6)
        self.t4_sg_4.setObjectName(u"t4_sg_4")
        self.t4_sg_4.setGeometry(QRect(115, 240, 550, 25))
        self.t4_sg_4.setMaximum(255)
        self.t4_sg_4.setPageStep(1)
        self.t4_sg_4.setOrientation(Qt.Horizontal)
        self.label_23 = QLabel(self.tab_6)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(30, 60, 81, 25))
        self.t4_s1_4 = QSlider(self.tab_6)
        self.t4_s1_4.setObjectName(u"t4_s1_4")
        self.t4_s1_4.setGeometry(QRect(115, 60, 550, 25))
        self.t4_s1_4.setMaximum(1000)
        self.t4_s1_4.setPageStep(1)
        self.t4_s1_4.setTracking(True)
        self.t4_s1_4.setOrientation(Qt.Horizontal)
        self.t4_s1_4.setTickPosition(QSlider.NoTicks)
        self.t4_s1_4.setTickInterval(0)
        self.label_24 = QLabel(self.tab_6)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(30, 25, 81, 25))
        self.t4_13 = QLineEdit(self.tab_6)
        self.t4_13.setObjectName(u"t4_13")
        self.t4_13.setGeometry(QRect(680, 25, 81, 25))
        self.label_25 = QLabel(self.tab_6)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(30, 205, 81, 25))
        self.t4_14 = QLineEdit(self.tab_6)
        self.t4_14.setObjectName(u"t4_14")
        self.t4_14.setGeometry(QRect(680, 95, 81, 25))
        self.t4_s0_4 = QSlider(self.tab_6)
        self.t4_s0_4.setObjectName(u"t4_s0_4")
        self.t4_s0_4.setGeometry(QRect(115, 25, 550, 25))
        self.t4_s0_4.setMaximum(100)
        self.t4_s0_4.setPageStep(1)
        self.t4_s0_4.setOrientation(Qt.Horizontal)
        self.t4_sr_4 = QSlider(self.tab_6)
        self.t4_sr_4.setObjectName(u"t4_sr_4")
        self.t4_sr_4.setGeometry(QRect(115, 205, 550, 25))
        self.t4_sr_4.setMaximum(255)
        self.t4_sr_4.setPageStep(1)
        self.t4_sr_4.setOrientation(Qt.Horizontal)
        self.label_26 = QLabel(self.tab_6)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(30, 275, 81, 25))
        self.label_27 = QLabel(self.tab_6)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(30, 130, 81, 25))
        self.label_28 = QLabel(self.tab_6)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(30, 240, 81, 25))
        self.t4_g_4 = QLineEdit(self.tab_6)
        self.t4_g_4.setObjectName(u"t4_g_4")
        self.t4_g_4.setGeometry(QRect(680, 240, 81, 25))
        self.t4_15 = QLineEdit(self.tab_6)
        self.t4_15.setObjectName(u"t4_15")
        self.t4_15.setGeometry(QRect(680, 60, 81, 25))
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.t4_s1 = QSlider(self.tab_5)
        self.t4_s1.setObjectName(u"t4_s1")
        self.t4_s1.setGeometry(QRect(115, 60, 550, 25))
        self.t4_s1.setMaximum(1000)
        self.t4_s1.setPageStep(1)
        self.t4_s1.setTracking(True)
        self.t4_s1.setOrientation(Qt.Horizontal)
        self.t4_s1.setTickPosition(QSlider.NoTicks)
        self.t4_s1.setTickInterval(0)
        self.t4_s2 = QSlider(self.tab_5)
        self.t4_s2.setObjectName(u"t4_s2")
        self.t4_s2.setGeometry(QRect(115, 95, 550, 25))
        self.t4_s2.setMaximum(500)
        self.t4_s2.setPageStep(1)
        self.t4_s2.setOrientation(Qt.Horizontal)
        self.t4_s3 = QSlider(self.tab_5)
        self.t4_s3.setObjectName(u"t4_s3")
        self.t4_s3.setGeometry(QRect(115, 130, 550, 25))
        self.t4_s3.setMaximum(250)
        self.t4_s3.setPageStep(1)
        self.t4_s3.setOrientation(Qt.Horizontal)
        self.label = QLabel(self.tab_5)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 95, 81, 25))
        self.label_2 = QLabel(self.tab_5)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 60, 81, 25))
        self.label_3 = QLabel(self.tab_5)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 130, 81, 25))
        self.t4_sg = QSlider(self.tab_5)
        self.t4_sg.setObjectName(u"t4_sg")
        self.t4_sg.setGeometry(QRect(115, 240, 550, 25))
        self.t4_sg.setMaximum(255)
        self.t4_sg.setPageStep(1)
        self.t4_sg.setOrientation(Qt.Horizontal)
        self.t4_sb = QSlider(self.tab_5)
        self.t4_sb.setObjectName(u"t4_sb")
        self.t4_sb.setGeometry(QRect(115, 275, 550, 25))
        self.t4_sb.setMaximum(255)
        self.t4_sb.setPageStep(1)
        self.t4_sb.setOrientation(Qt.Horizontal)
        self.t4_sr = QSlider(self.tab_5)
        self.t4_sr.setObjectName(u"t4_sr")
        self.t4_sr.setGeometry(QRect(115, 205, 550, 25))
        self.t4_sr.setMaximum(255)
        self.t4_sr.setPageStep(1)
        self.t4_sr.setOrientation(Qt.Horizontal)
        self.t4_s0 = QSlider(self.tab_5)
        self.t4_s0.setObjectName(u"t4_s0")
        self.t4_s0.setGeometry(QRect(115, 25, 550, 25))
        self.t4_s0.setMaximum(1000)
        self.t4_s0.setPageStep(1)
        self.t4_s0.setOrientation(Qt.Horizontal)
        self.label_4 = QLabel(self.tab_5)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 205, 81, 25))
        self.label_5 = QLabel(self.tab_5)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 240, 81, 25))
        self.label_6 = QLabel(self.tab_5)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 275, 81, 25))
        self.label_7 = QLabel(self.tab_5)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 25, 81, 25))
        self.t4_1 = QLineEdit(self.tab_5)
        self.t4_1.setObjectName(u"t4_1")
        self.t4_1.setGeometry(QRect(680, 60, 81, 25))
        self.t4_2 = QLineEdit(self.tab_5)
        self.t4_2.setObjectName(u"t4_2")
        self.t4_2.setGeometry(QRect(680, 95, 81, 25))
        self.t4_3 = QLineEdit(self.tab_5)
        self.t4_3.setObjectName(u"t4_3")
        self.t4_3.setGeometry(QRect(680, 130, 81, 25))
        self.t4_r = QLineEdit(self.tab_5)
        self.t4_r.setObjectName(u"t4_r")
        self.t4_r.setGeometry(QRect(680, 205, 81, 25))
        self.t4_g = QLineEdit(self.tab_5)
        self.t4_g.setObjectName(u"t4_g")
        self.t4_g.setGeometry(QRect(680, 240, 81, 25))
        self.t4_b = QLineEdit(self.tab_5)
        self.t4_b.setObjectName(u"t4_b")
        self.t4_b.setGeometry(QRect(680, 275, 81, 25))
        self.t4_0 = QLineEdit(self.tab_5)
        self.t4_0.setObjectName(u"t4_0")
        self.t4_0.setGeometry(QRect(680, 25, 81, 25))
        self.tabWidget.addTab(self.tab_5, "")

        self.verticalLayout.addWidget(self.tabWidget)


        self.retranslateUi(MaterialDialog)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MaterialDialog)
    # setupUi

    def retranslateUi(self, MaterialDialog):
        MaterialDialog.setWindowTitle(QCoreApplication.translate("MaterialDialog", u"Messages", None))
        self.lg2.setText(QCoreApplication.translate("MaterialDialog", u"G", None))
        self.lb2.setText(QCoreApplication.translate("MaterialDialog", u"B", None))
        self.lr2.setText(QCoreApplication.translate("MaterialDialog", u"R", None))
        self.lb0.setText(QCoreApplication.translate("MaterialDialog", u"Linear", None))
        self.l0.setText(QCoreApplication.translate("MaterialDialog", u"Alpha", None))
        self.lr0.setText(QCoreApplication.translate("MaterialDialog", u"Intesity", None))
        self.lg0.setText(QCoreApplication.translate("MaterialDialog", u"Constant", None))
        self.lg1.setText(QCoreApplication.translate("MaterialDialog", u"G", None))
        self.lr1.setText(QCoreApplication.translate("MaterialDialog", u"R", None))
        self.lb1.setText(QCoreApplication.translate("MaterialDialog", u"B", None))
        self.l1.setText(QCoreApplication.translate("MaterialDialog", u"Alpha", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MaterialDialog", u"Material", None))
        self.label_15.setText(QCoreApplication.translate("MaterialDialog", u"Linear", None))
        self.label_16.setText(QCoreApplication.translate("MaterialDialog", u"Constant", None))
        self.label_17.setText(QCoreApplication.translate("MaterialDialog", u"Intesity", None))
        self.label_18.setText(QCoreApplication.translate("MaterialDialog", u"R", None))
        self.label_19.setText(QCoreApplication.translate("MaterialDialog", u"B", None))
        self.label_20.setText(QCoreApplication.translate("MaterialDialog", u"Quadratic", None))
        self.label_21.setText(QCoreApplication.translate("MaterialDialog", u"G", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QCoreApplication.translate("MaterialDialog", u"DirectionalLight", None))
        self.label_22.setText(QCoreApplication.translate("MaterialDialog", u"Linear", None))
        self.label_23.setText(QCoreApplication.translate("MaterialDialog", u"Constant", None))
        self.label_24.setText(QCoreApplication.translate("MaterialDialog", u"Intesity", None))
        self.label_25.setText(QCoreApplication.translate("MaterialDialog", u"R", None))
        self.label_26.setText(QCoreApplication.translate("MaterialDialog", u"B", None))
        self.label_27.setText(QCoreApplication.translate("MaterialDialog", u"Quadratic", None))
        self.label_28.setText(QCoreApplication.translate("MaterialDialog", u"G", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("MaterialDialog", u"SpotLight", None))
        self.label.setText(QCoreApplication.translate("MaterialDialog", u"Linear", None))
        self.label_2.setText(QCoreApplication.translate("MaterialDialog", u"Constant", None))
        self.label_3.setText(QCoreApplication.translate("MaterialDialog", u"Quadratic", None))
        self.label_4.setText(QCoreApplication.translate("MaterialDialog", u"R", None))
        self.label_5.setText(QCoreApplication.translate("MaterialDialog", u"G", None))
        self.label_6.setText(QCoreApplication.translate("MaterialDialog", u"B", None))
        self.label_7.setText(QCoreApplication.translate("MaterialDialog", u"Intesity", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("MaterialDialog", u"PointLight", None))
    # retranslateUi

