# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './mw4/gui/widgets/mount3D.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mount3DDialog(object):
    def setupUi(self, Mount3DDialog):
        Mount3DDialog.setObjectName("Mount3DDialog")
        Mount3DDialog.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Mount3DDialog.sizePolicy().hasHeightForWidth())
        Mount3DDialog.setSizePolicy(sizePolicy)
        Mount3DDialog.setMinimumSize(QtCore.QSize(800, 600))
        Mount3DDialog.setMaximumSize(QtCore.QSize(1600, 1200))
        Mount3DDialog.setSizeIncrement(QtCore.QSize(10, 10))
        Mount3DDialog.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        Mount3DDialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Mount3DDialog)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(Mount3DDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setProperty("large", True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setContentsMargins(0, 8, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.mountX = QtWidgets.QWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mountX.sizePolicy().hasHeightForWidth())
        self.mountX.setSizePolicy(sizePolicy)
        self.mountX.setObjectName("mountX")
        self.gridLayout_5.addWidget(self.mountX, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(Mount3DDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setProperty("large", True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setContentsMargins(0, 8, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.mountY = QtWidgets.QWidget(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mountY.sizePolicy().hasHeightForWidth())
        self.mountY.setSizePolicy(sizePolicy)
        self.mountY.setObjectName("mountY")
        self.gridLayout_4.addWidget(self.mountY, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Mount3DDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setProperty("large", True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(0, 8, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mountTop = QtWidgets.QWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mountTop.sizePolicy().hasHeightForWidth())
        self.mountTop.setSizePolicy(sizePolicy)
        self.mountTop.setMinimumSize(QtCore.QSize(0, 0))
        self.mountTop.setObjectName("mountTop")
        self.gridLayout_2.addWidget(self.mountTop, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Mount3DDialog)
        self.groupBox_2.setProperty("large", True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mount3d = QtWidgets.QWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mount3d.sizePolicy().hasHeightForWidth())
        self.mount3d.setSizePolicy(sizePolicy)
        self.mount3d.setObjectName("mount3d")
        self.gridLayout_3.addWidget(self.mount3d, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)

        self.retranslateUi(Mount3DDialog)
        QtCore.QMetaObject.connectSlotsByName(Mount3DDialog)

    def retranslateUi(self, Mount3DDialog):
        _translate = QtCore.QCoreApplication.translate
        Mount3DDialog.setWindowTitle(_translate("Mount3DDialog", "Mount Simulation View"))
        self.groupBox_3.setTitle(_translate("Mount3DDialog", "Looking from X"))
        self.mountX.setToolTip(_translate("Mount3DDialog", "Shows the satellite path vertical over ground."))
        self.groupBox_4.setTitle(_translate("Mount3DDialog", "Looking from Y"))
        self.mountY.setToolTip(_translate("Mount3DDialog", "Shows the visible track of the satellite when being observed from the position of the mount. "))
        self.groupBox.setTitle(_translate("Mount3DDialog", "Looking from Top"))
        self.mountTop.setToolTip(_translate("Mount3DDialog", "Show the satellite path in orbit. The observer is a fixed place with the coordinates of the mount. The earth is not turning. therefore we get normally a spiral path for the satellite."))
        self.groupBox_2.setTitle(_translate("Mount3DDialog", "Looking ISO"))
        self.mount3d.setToolTip(_translate("Mount3DDialog", "Shows the visible track of the satellite when being observed from the position of the mount. "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mount3DDialog = QtWidgets.QWidget()
    ui = Ui_Mount3DDialog()
    ui.setupUi(Mount3DDialog)
    Mount3DDialog.show()
    sys.exit(app.exec_())
