# Form implementation generated from reading ui file './mw4/gui/widgets/uploadPopup.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UploadPopup(object):
    def setupUi(self, UploadPopup):
        UploadPopup.setObjectName("UploadPopup")
        UploadPopup.resize(400, 80)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(UploadPopup.sizePolicy().hasHeightForWidth())
        UploadPopup.setSizePolicy(sizePolicy)
        UploadPopup.setMinimumSize(QtCore.QSize(400, 0))
        UploadPopup.setMaximumSize(QtCore.QSize(400, 80))
        UploadPopup.setSizeIncrement(QtCore.QSize(10, 10))
        UploadPopup.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        UploadPopup.setFont(font)
        self.progressBar = QtWidgets.QProgressBar(parent=UploadPopup)
        self.progressBar.setGeometry(QtCore.QRect(10, 10, 376, 26))
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.Direction.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.statusText = QtWidgets.QLineEdit(parent=UploadPopup)
        self.statusText.setGeometry(QtCore.QRect(15, 45, 371, 21))
        self.statusText.setObjectName("statusText")

        self.retranslateUi(UploadPopup)
        QtCore.QMetaObject.connectSlotsByName(UploadPopup)

    def retranslateUi(self, UploadPopup):
        _translate = QtCore.QCoreApplication.translate
        UploadPopup.setWindowTitle(_translate("UploadPopup", "Device Setup"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UploadPopup = QtWidgets.QWidget()
    ui = Ui_UploadPopup()
    ui.setupUi(UploadPopup)
    UploadPopup.show()
    sys.exit(app.exec())
