# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './mw4/gui/widgets/video.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VideoDialog(object):
    def setupUi(self, VideoDialog):
        VideoDialog.setObjectName("VideoDialog")
        VideoDialog.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VideoDialog.sizePolicy().hasHeightForWidth())
        VideoDialog.setSizePolicy(sizePolicy)
        VideoDialog.setMinimumSize(QtCore.QSize(400, 285))
        VideoDialog.setMaximumSize(QtCore.QSize(800, 600))
        VideoDialog.setSizeIncrement(QtCore.QSize(10, 10))
        VideoDialog.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        VideoDialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(VideoDialog)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(VideoDialog)
        self.label.setMinimumSize(QtCore.QSize(0, 21))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 5, 1, 1)
        self.streamStop = QtWidgets.QPushButton(VideoDialog)
        self.streamStop.setMinimumSize(QtCore.QSize(80, 21))
        self.streamStop.setMaximumSize(QtCore.QSize(100, 25))
        self.streamStop.setProperty("running", False)
        self.streamStop.setObjectName("streamStop")
        self.gridLayout.addWidget(self.streamStop, 0, 3, 1, 1)
        self.streamStart = QtWidgets.QPushButton(VideoDialog)
        self.streamStart.setMinimumSize(QtCore.QSize(80, 21))
        self.streamStart.setMaximumSize(QtCore.QSize(100, 25))
        self.streamStart.setObjectName("streamStart")
        self.gridLayout.addWidget(self.streamStart, 0, 2, 1, 1)
        self.streamSource = QtWidgets.QComboBox(VideoDialog)
        self.streamSource.setMinimumSize(QtCore.QSize(150, 21))
        self.streamSource.setMaximumSize(QtCore.QSize(16777215, 25))
        self.streamSource.setObjectName("streamSource")
        self.streamSource.addItem("")
        self.streamSource.addItem("")
        self.streamSource.addItem("")
        self.gridLayout.addWidget(self.streamSource, 0, 4, 1, 1)
        self.streamURL = QtWidgets.QLineEdit(VideoDialog)
        self.streamURL.setMinimumSize(QtCore.QSize(250, 21))
        self.streamURL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.streamURL.setObjectName("streamURL")
        self.gridLayout.addWidget(self.streamURL, 1, 2, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtWidgets.QFrame(VideoDialog)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setMidLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.video = QtWidgets.QLabel(VideoDialog)
        self.video.setText("")
        self.video.setObjectName("video")
        self.verticalLayout.addWidget(self.video)
        self.verticalLayout.setStretch(2, 1)

        self.retranslateUi(VideoDialog)
        QtCore.QMetaObject.connectSlotsByName(VideoDialog)

    def retranslateUi(self, VideoDialog):
        _translate = QtCore.QCoreApplication.translate
        VideoDialog.setWindowTitle(_translate("VideoDialog", "Video Streams"))
        self.label.setText(_translate("VideoDialog", "URL"))
        self.streamStop.setText(_translate("VideoDialog", "Stop"))
        self.streamStart.setText(_translate("VideoDialog", "Start"))
        self.streamSource.setItemText(0, _translate("VideoDialog", "RTSP Stream"))
        self.streamSource.setItemText(1, _translate("VideoDialog", "Camera 1"))
        self.streamSource.setItemText(2, _translate("VideoDialog", "Camera 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VideoDialog = QtWidgets.QWidget()
    ui = Ui_VideoDialog()
    ui.setupUi(VideoDialog)
    VideoDialog.show()
    sys.exit(app.exec_())
