############################################################
# -*- coding: utf-8 -*-
#
#       #   #  #   #   #    #
#      ##  ##  #  ##  #    #
#     # # # #  # # # #    #  #
#    #  ##  #  ##  ##    ######
#   #   #   #  #   #       #
#
# Python-based Tool for interaction with the 10micron mounts
# GUI with PyQT5 for python
# Python  v3.7.4
#
# Michael Würtenberger
# (c) 2019
#
# Licence APL2.0
#
###########################################################
# standard libraries
from unittest import mock
import pytest
import shutil
import subprocess
# external packages
# local import
from mw4.astrometry import astrometry
from mw4.test.test_units.setupQt import setupQt


@pytest.fixture(autouse=True, scope='module')
def module_setup_teardown():
    global app, spy, mwGlob, test
    app, spy, mwGlob, test = setupQt()
    yield


def test_getWCSHeaderASTAP_1():

    val = """SIMPLE  =                    T / file does conform to FITS standard             
BITPIX  =                   16 / number of bits per data pixel                  
NAXIS   =                    2 / number of data axes                            
NAXIS1  =                 3388 / length of data axis 1                          
NAXIS2  =                 2712 / length of data axis 2                          
EXTEND  =                    T / FITS dataset may contain extensions            
COMMENT   FITS (Flexible Image Transport System) format is defined in 'Astronomy
COMMENT   and Astrophysics', volume 376, page 359; bibcode: 2001A&A...376..359H 
BSCALE  =                    1 / default scaling factor                         
BZERO   =                32768 / offset data range to that of unsigned short    
INSTRUME= 'QSI CCD '           / CCD Name                                       
TELESCOP= 'LX200 10micron'     / Telescope name                                 
OBSERVER= 'Wuertenberger Michael' / Observer name                               
OBJECT  = 'ced214  '           / Object name                                    
EXPTIME =         9.000000E+02 / Total Exposure Time (s)                        
CCD-TEMP=            -2.00E+01 / CCD Temperature (Celsius)                      
PIXSIZE1=         3.690000E+00 / Pixel Size 1 (microns)                         
PIXSIZE2=         3.690000E+00 / Pixel Size 2 (microns)                         
XBINNING=                    1 / Binning factor in width                        
YBINNING=                    1 / Binning factor in height                       
FRAME   = 'Light   '           / Frame Type                                     
FILTER  = 'Ha      '           / Filter                                         
FOCALLEN=             5.80E+02 / Focal Length (mm)                              
MPSAS   =         2.009000E+01 / Sky Quality (mag per arcsec^2)                 
SCALE   =         1.312495E+00 / arcsecs per pixel                              
SITELAT =         4.803333E+01 / Latitude of the imaging site in degrees        
SITELONG=         1.170000E+01 / Longitude of the imaging site in degrees       
AIRMASS =         1.062458E+00 / Airmass                                        
OBJCTRA = ' 0 02 02.66'        / Object J2000 RA in Hours                       
OBJCTDEC= '67 12 00.49'        / Object J2000 DEC in Degrees                    
RA      =         5.110954E-01 / Object J2000 RA in Degrees                     
DEC     =         6.720014E+01 / Object J2000 DEC in Degrees                    
EQUINOX =                 2000 / Equinox                                        
DATE-OBS= '2018-10-13T21:12:41.560Z' / UTC start date of observation            
COMMENT Generated by INDI                                                       
EPERADU =                0.251 / Electrons per ADU                              
CTYPE1  = 'RA---TAN'           / first parameter RA  ,  projection TANgential   
CTYPE2  = 'DEC--TAN'           / second parameter DEC,  projection TANgential   
CUNIT1  = 'deg     '           / Unit of coordinates                            
CRPIX1  =  1.694500000000E+003 / X of reference pixel                           
CRPIX2  =  1.356500000000E+003 / Y of reference pixel                           
CRVAL1  =  4.974019243995E-001 / RA of reference pixel (deg)                    
CRVAL2  =  6.719678142676E+001 / DEC of reference pixel (deg)                   
CDELT1  =  3.670354773032E-004 / X pixel size (deg)                             
CDELT2  =  3.670205615613E-004 / Y pixel size (deg)                             
CROTA1  = -9.093965496476E+001 / Image twist of X axis        (deg)             
CROTA2  = -9.092633081546E+001 / Image twist of Y axis        (deg)             
CD1_1   = -5.933795895754E-006 / CD matrix to convert (x,y) to (Ra, Dec)        
CD1_2   = -3.669712053032E-004 / CD matrix to convert (x,y) to (Ra, Dec)        
CD2_1   =  3.669875088684E-004 / CD matrix to convert (x,y) to (Ra, Dec)        
CD2_2   = -6.018894172420E-006 / CD matrix to convert (x,y) to (Ra, Dec)        
PLTSOLVD=                    T / ASTAP internal solver                          
COMMENT 1  Solved in 1.4 sec. Offset was 0.006 deg.                             
END                                                                             """

    file = mwGlob['tempDir'] + '/astap.wcs'
    with open(file) as fileHandle:
        wcsHeader = app.astrometry.getWCSHeader(wcsTextFile=fileHandle)
    assert wcsHeader.tostring(sep='\n', endcard=True, padding=False) == val


def test_solve_1():
    suc = app.astrometry.solveASTAP()
    assert not suc


def test_solve_2():
    with mock.patch.object(app.astrometry,
                           'runASTAP',
                           return_value=False):
        suc = app.astrometry.solveASTAP(app='ASTAP',
                                        fitsPath=mwGlob['imageDir'] + '/nonsolve.fits',
                                        timeout=5,
                                        )
    assert not suc


def test_solve_3():
    with mock.patch.object(app.astrometry,
                           'runASTAP',
                           return_value=True):
        suc = app.astrometry.solveASTAP(app='ASTAP',
                                        fitsPath=mwGlob['imageDir'] + '/nonsolve.fits',
                                        timeout=5,
                                        )
    assert not suc


def test_solve_4():
    app.astrometry.solveApp = {
        'ASTAP': {
            'programPath': '/Applications/ASTAP.app/Contents/MacOS',
            'indexPath': '/Applications/ASTAP.app/Contents/MacOS',
            'solve': app.astrometry.solveASTAP,
            'abort': app.astrometry.abortASTAP,
        }
    }
    with mock.patch.object(app.astrometry,
                           'runASTAP',
                           return_value=True):
        suc = app.astrometry.solveASTAP(app='ASTAP',
                                        fitsPath=mwGlob['imageDir'] + '/m51.fits',
                                        timeout=5,
                                        )
    assert not suc


def test_solve_5():
    src = mwGlob['tempDir'] + '/m51.wcs'
    dest = mwGlob['imageDir'] + '/temp.wcs'
    shutil.copyfile(src, dest)
    app.astrometry.solveApp = {
        'ASTAP': {
            'programPath': '/Applications/ASTAP.app/Contents/MacOS',
            'indexPath': '/Applications/ASTAP.app/Contents/MacOS',
            'solve': app.astrometry.solveASTAP,
            'abort': app.astrometry.abortASTAP,
        }
    }
    with mock.patch.object(app.astrometry,
                           'runASTAP',
                           return_value=True):
        suc = app.astrometry.solveASTAP(app='ASTAP',
                                        fitsPath=mwGlob['imageDir'] + '/m51.fits',
                                        timeout=5,
                                        )
        assert suc


def test_abort_1():
    app.astrometry.process = None
    suc = app.astrometry.abortASTAP()
    assert not suc


def test_abort_2():
    class Test:
        @staticmethod
        def kill():
            return True
    app.astrometry.process = Test()
    suc = app.astrometry.abortASTAP()
    assert suc
