#
# v1.0, Michael Wuertenberger
#
name: setup test
description: download package install and install test environment

runs:
  using: 'composite'
  steps:
    - name: download dist
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist
    
    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: install #1
      run: |
        python -m pip install cython wheel
        python -m pip install pyqt5-sip==12.12.2
        python -m pip install pyqt5==5.15.9
        python -m pip install dist/mountwizzard4.tar.gz
        python -m pip install pytest
        python -m pip install pytest-qt
        python -m pip install pytest-cov
        python -m pip install pytest-pythonpath
      shell: bash
