############################################################
# -*- coding: utf-8 -*-
#
#       #   #  #   #   #    #
#      ##  ##  #  ##  #    #
#     # # # #  # # # #    #  #
#    #  ##  #  ##  ##    ######
#   #   #   #  #   #       #
#
# Python-based Tool for interaction with the 10micron mounts
# GUI with PyQT5 for python3
#
# written in python3, (c) 2019-2025 by mworion
# Licence APL2.0
#
###########################################################

name: setup test
description: download package install and install test environment

runs:
  using: 'composite'
  steps:
    - name: install uv
      uses: astral-sh/setup-uv@v8.2.0
      with:
        enable-cache: true
        python-version: '3.14'

    - name: install #1
      run: |
        uv sync --locked --dev
        uv pip install pytest pytest-qt pytest-xvfb
      shell: bash
