############################################################
# -*- coding: utf-8 -*-
#
#       #   #  #   #   #    #
#      ##  ##  #  ##  #    #
#     # # # #  # # # #    #  #
#    #  ##  #  ##  ##    ######
#   #   #   #  #   #       #
#
# Python-based Tool for interaction with the 10micron mounts
# GUI with PyQT5 for python3
#
# written in python3, (c) 2019-2025 by mworion
# Licence APL2.0
#
###########################################################

name: setup test
description: download package install and install test environment

runs:
  using: 'composite'
  steps:
    - name: install uv
      uses: astral-sh/setup-uv@v8
      with:
        enable-cache: true
        python-version: '3.13'

    - name: install #1
      run: |
        uv venv -p 3.13
        uv pip install -e .
        uv pip install pip --upgrade
        uv pip install cython wheel
        uv pip install pytest pytest-qt pytest-cov pytest-xvfb pytest-forked
      shell: bash
