#
# v1.0, Michael Wuertenberger
#
name: setup test
description: download package install and install test environment

runs:
  using: 'composite'
  steps:
    - name: download dist
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist
    
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: install #0
      run: python -m pip install pip --upgrade
      shell: bash
    
    - name: install #1
      run: python -m pip install cython wheel
      shell: bash
    
    - name: install #2
      run: python -m pip install dist/mountwizzard4.tar.gz
      shell: bash
    
    - name: install #3
      run: python -m pip install pytest
      shell: bash
    
    - name: install #4
      run: python -m pip install pytest-qt
      shell: bash
    
    - name: install #5
      run: python -m pip install pytest-pythonpath
      shell: bash
