############################################################
# -*- coding: utf-8 -*-
#
#       #   #  #   #   #    #
#      ##  ##  #  ##  #    #
#     # # # #  # # # #    #  #
#    #  ##  #  ##  ##    ######
#   #   #   #  #   #       #
#
# Python-based Tool for interaction with the 10micron mounts
# GUI with PyQT5 for python3
#
# written in python3, (c) 2019-2025 by mworion
# Licence APL2.0
#
###########################################################

name: setup test coverage
description: download package install and install test environment for coverage

runs:
  using: 'composite'
  steps:

    - name: install uv
      uses: astral-sh/setup-uv@v8.2.0
      with:
        enable-cache: true
        python-version: '3.14'

    - name: install #1
      run: |        
        uv venv -p 3.14
        uv pip install -e .
        uv pip install comtypes==1.4.16 pytest pytest-qt pytest-cov pytest-xvfb
      shell: bash
