############################################################
# -*- coding: utf-8 -*-
#
#       #   #  #   #   #    #
#      ##  ##  #  ##  #    #
#     # # # #  # # # #    #  #
#    #  ##  #  ##  ##    ######
#   #   #   #  #   #       #
#
# Python-based Tool for interaction with the 10micron mounts
# GUI with PyQT5 for python3
#
# written in python3, (c) 2019-2025 by mworion
# Licence APL2.0
#
###########################################################

name: setup test coverage
description: download package install and install test environment for coverage

runs:
  using: 'composite'
  steps:
    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: install #1
      run: |
        python -m pip install -e .
        python -m pip install cython wheel
        python -m pip install comtypes==1.2.1
        python -m pip install pytest
        python -m pip install pytest-qt
        python -m pip install pytest-cov
      shell: bash
