#
# v1.0, Michael Wuertenberger
#
name: setup test coverage
description: download package install and install test environment for coverage

runs:
  using: 'composite'
  steps:
    - name: download dist
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: install #1
      run: python -m pip install cython wheel
      shell: bash

    - name: install #2
      run: python -m pip install dist/mountwizzard4.tar.gz
      shell: bash

    - name: install #3
      run:  python -m pip install comtypes==1.1.11
      shell: bash

    - name: install #4
      run:  python -m pip install pytest
      shell: bash

    - name: install #5
      run:  python -m pip install pytest-qt
      shell: bash

    - name: install #6
      run:  python -m pip install pytest-cov
      shell: bash

    - name: install #7
      run:  python -m pip install pytest-pythonpath
      shell: bash
