#
# v1.0, Michael Wuertenberger
#
name: build_package
description: build package and uploads as artifact

runs:
  using: 'composite'
  
  steps:
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: install #1
      run: python -m pip install setuptools wheel
      shell: bash
      
    - name: install #2
      run: python setup.py sdist
      shell: bash
      
    - name: install #3
      run: mv dist/mountwizzard4*.* dist/mountwizzard4.tar.gz
      shell: bash

    - name: upload package
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
