#
# v1.0, Michael Wuertenberger
#
name: build_package
description: build package and uploads as artifact

runs:
  using: 'composite'
  
  steps:
    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: install #1
      run: |
        python -m pip install setuptools wheel
        python -m pip install pyqt5-sip==12.12.2
        python setup.py sdist
        mv dist/mountwizzard4*.* dist/mountwizzard4.tar.gz
      shell: bash

    - name: upload package
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist
