bigPopupW:
  height: 265
  width: 380
  winPosX: 556
  winPosY: 337
colorSet: 0
driversData:
  camera:
    framework: indi
    frameworks:
      alpaca:
        apiVersion: 1
        deviceList: []
        deviceName: ''
        hostaddress: localhost
        password: ''
        port: 11111
        updateRate: 1000
        user: ''
      indi:
        deviceList:
        - CCD Simulator
        deviceName: CCD Simulator
        hostaddress: localhost
        loadConfig: true
        messages: true
        port: 7624
        updateRate: 1000.0
  cover:
    framework: ''
    frameworks:
      alpaca:
        apiVersion: 1
        deviceList: []
        deviceName: ''
        hostaddress: localhost
        password: ''
        port: 11111
        updateRate: 1000
        user: ''
      indi:
        deviceList: []
        deviceName: ''
        hostaddress: localhost
        loadConfig: true
        messages: true
        port: 7624
        updateRate: 1000.0
  directWeather:
    framework: ''
    frameworks:
      directWeather:
        deviceName: On Mount
  dome:
    framework: indi
    frameworks:
      alpaca:
        apiVersion: 1
        deviceList: []
        deviceName: ''
        hostaddress: localhost
        password: ''
        port: 11111
        updateRate: 1000
        user: ''
      indi:
        deviceList:
        - Dome Simulator
        deviceName: Dome Simulator
        hostaddress: localhost
        loadConfig: true
        messages: false
        port: 7624
        updateRate: 1000.0
  filter:
    framework: indi
    frameworks:
      alpaca:
        apiVersion: 1
        deviceList: []
        deviceName: ''
        hostaddress: localhost
        password: ''
        port: 11111
        updateRate: 1000
        user: ''
      indi:
        deviceList:
        - CCD Simulator
        deviceName: CCD Simulator
        hostaddress: localhost
        loadConfig: true
        messages: false
        port: 7624
        updateRate: 1000.0
  focuser:
    framework: ''
    frameworks:
      alpaca:
        apiVersion: 1
        deviceList: []
        deviceName: ''
        hostaddress: localhost
        password: ''
        port: 11111
        updateRate: 1000
        user: ''
      indi:
        deviceList: []
        deviceName: ''
        hostaddress: localhost
        loadConfig: true
        messages: true
        port: 7624
        updateRate: 1000.0
  measure:
    framework: ''
    frameworks:
      csv:
        deviceName: save to file
      raw:
        deviceName: display only
  plateSolve:
    framework: ''
    frameworks:
      astap:
        appPath: /Applications/ASTAP.app/Contents/MacOS
        deviceList:
        - ASTAP
        deviceName: ASTAP
        indexPath: /usr/local/opt/astap
        searchRadius: 20.0
        timeout: 30.0
      astrometry:
        appPath: /Applications/KStars.app/Contents/MacOS/astrometry/bin
        deviceList:
        - ASTROMETRY.NET
        deviceName: ASTROMETRY.NET
        indexPath: /Users/Q115346/Library/Application Support/Astrometry
        searchRadius: 10
        timeout: 30
      watney:
        appPath: /Users/Q115346/PycharmProjects/MountWizzard4/work/watney-cli
        deviceList:
        - Watney
        deviceName: Watney
        indexPath: /Users/Q115346/PycharmProjects/MountWizzard4/work/watney-index
        searchRadius: 10
        timeout: 30
  power:
    framework: ''
    frameworks:
      alpaca:
        apiVersion: 1
        deviceList: []
        deviceName: ''
        hostaddress: localhost
        password: ''
        port: 11111
        updateRate: 1000
        user: ''
      indi:
        deviceList: []
        deviceName: ''
        hostaddress: localhost
        loadConfig: true
        messages: true
        port: 7624
        updateRate: 1000.0
  relay:
    framework: ''
    frameworks:
      relay:
        deviceName: KMRelay
        hostaddress: ''
        password: ''
        user: ''
  remote:
    framework: ''
    frameworks:
      tcp:
        deviceName: TCP
  seeingWeather:
    framework: ''
    frameworks:
      seeing:
        apiKey: free
        deviceName: meteoblue
        hostaddress: my.meteoblue.com
  sensor1Weather:
    framework: ''
    frameworks:
      alpaca:
        apiVersion: 1
        deviceList: []
        deviceName: ''
        hostaddress: localhost
        password: ''
        port: 11111
        updateRate: 1000
        user: ''
      boltwood:
        deviceName: Boltwood II
        filePath: ''
      indi:
        deviceList: []
        deviceName: ''
        hostaddress: localhost
        loadConfig: true
        messages: true
        port: 7624
        updateRate: 1000.0
      online:
        apiKey: ''
        deviceName: OnlineWeather
        hostaddress: api.openweathermap.org
  sensor2Weather:
    framework: ''
    frameworks:
      alpaca:
        apiVersion: 1
        deviceList: []
        deviceName: ''
        hostaddress: localhost
        password: ''
        port: 11111
        updateRate: 1000
        user: ''
      boltwood:
        deviceName: Boltwood II
        filePath: ''
      indi:
        deviceList: []
        deviceName: ''
        hostaddress: localhost
        loadConfig: true
        messages: true
        port: 7624
        updateRate: 1000.0
      online:
        apiKey: ''
        deviceName: OnlineWeather
        hostaddress: api.openweathermap.org
  sensor3Weather:
    framework: ''
    frameworks:
      alpaca:
        apiVersion: 1
        deviceList: []
        deviceName: ''
        hostaddress: localhost
        password: ''
        port: 11111
        updateRate: 1000
        user: ''
      boltwood:
        deviceName: Boltwood II
        filePath: ''
      indi:
        deviceList: []
        deviceName: ''
        hostaddress: localhost
        loadConfig: true
        messages: true
        port: 7624
        updateRate: 1000.0
      online:
        apiKey: ''
        deviceName: OnlineWeather
        hostaddress: api.openweathermap.org
  sensor4Weather:
    framework: ''
    frameworks:
      alpaca:
        apiVersion: 1
        deviceList: []
        deviceName: ''
        hostaddress: localhost
        password: ''
        port: 11111
        updateRate: 1000
        user: ''
      boltwood:
        deviceName: Boltwood II
        filePath: ''
      indi:
        deviceList: []
        deviceName: ''
        hostaddress: localhost
        loadConfig: true
        messages: true
        port: 7624
        updateRate: 1000.0
      online:
        apiKey: ''
        deviceName: OnlineWeather
        hostaddress: api.openweathermap.org
  telescope:
    framework: ''
    frameworks:
      alpaca:
        apiVersion: 1
        deviceList: []
        deviceName: ''
        hostaddress: localhost
        password: ''
        port: 11111
        updateRate: 1000
        user: ''
      indi:
        deviceList: []
        deviceName: ''
        hostaddress: localhost
        loadConfig: true
        messages: true
        port: 7624
        updateRate: 1000.0
hemisphereW:
  altitudeShift: 0.0
  azimuthShift: -25.0
  height: 600
  horizonMaskFileName: ''
  showAlignStar: false
  showCelestial: true
  showHorizon: true
  showIsoModel: false
  showMountLimits: false
  showPolar: false
  showSlewPath: false
  showTerrain: false
  tabWidget: 0
  terrainAlpha: 0.3
  terrainFileName: t1.jpg
  width: 800
  winPosX: 356
  winPosY: 180
imageW:
  aspectLocked: false
  autoSolve: true
  color: 0
  embedData: false
  flipH: false
  flipV: false
  height: 600
  imageFileName: /Users/Q115346/PycharmProjects/MountWizzard4/work/image/exposure.fits
  isoLayer: false
  offsetTiltAngle: 0.0
  photometryGroup: false
  showCrosshair: false
  showValues: false
  snTarget: 0
  tabImage: 0
  timeTagImage: false
  width: 800
  winPosX: 356
  winPosY: 180
loglevel: TRACE
mainW:
  ageDatabases: 1.0
  almanacPrediction: 4
  altitudeMax: 75.0
  altitudeMin: 30.0
  aperture: 100.0
  asteroidFilterText: ''
  asteroidSource: 1
  autoConnectASCOM: false
  autoDeleteHorizon: true
  autoDeleteMeridian: false
  automaticDome: false
  automaticTelescope: false
  automaticWOL: false
  avoidFlip: false
  avoidHorizon: false
  binning1: 1.0
  binningN: 1.0
  buildPFileName: ''
  clockSync: false
  cometFilterText: ''
  cometSource: 1
  conservativeTiming: true
  coordsJ2000: true
  coordsJNow: false
  ditherBuildPoints: false
  domeAutoFollowSat: false
  domeClearOpening: 0.4
  domeClearanceZenith: 0.2
  domeEastOffset: 0.0
  domeNorthOffset: 0.0
  domeOpeningHysteresis: 0.0
  domeRadius: 1.5
  domeVerticalOffset: 0.0
  exposureTime1: 1.0
  exposureTimeN: 1.0
  focalLength: 100.0
  focuserSteps: 100.0
  focuserStepsize: 100.0
  gameControllerGroup: false
  gameControllerList: 0
  iersSource: 0
  includeSubdirs: false
  isOnline: true
  keepGeneratedPoints: false
  meridianDistanceFlip: 5.0
  mountHost: ''
  mountMAC: ''
  mountWolAddress: 255.255.255.255
  mountWolPort: '9'
  moveDuration: 0
  moveStepSizeAltAz: 0
  mpcTab: 0
  newObjectName: ''
  noSort: true
  normalTiming: false
  numberBuildRetries: 0.0
  numberCelestialStepDEC: 15.0
  numberCelestialStepHA: 15.0
  numberDSOPoints: 15.0
  numberGridPointsCol: 6.0
  numberGridPointsRow: 5.0
  numberSpiral: 30.0
  offGEM: 0.0
  offLAT: 0.0
  optimizeOverall: false
  optimizeSingle: true
  orderImaging:
    '00': ManageImaging
    '01': StatisticsFormulae
    '02': reference
    index: 0
  orderMain:
    '00': Mount
    '01': Environ
    '02': Almanac
    '03': Modeling
    '04': Imaging
    '05': Satellite
    '06': MPC
    '07': Tools
    08: Settings
    index: 0
  orderManage:
    '00': ModelPositions
    '01': ErrorDistribution
    '02': ErrorAscending
    index: 0
  orderModeling:
    '00': GenerateBuildPoints
    '01': ModelBuildProgram
    '02': ManageModels
    index: 0
  orderMount:
    '00': SettingsMount
    '01': PosCoordinates
    '02': SlewRaDec
    '03': MountTerminal
    index: 0
  orderSatellite:
    '00': Searching
    '01': Tracking
    index: 0
  orderSettings:
    '00': Devices
    '01': MountRemote
    '02': Dome
    '03': ParkPos
    '04': RelaySett
    '05': Profile
    '06': Gui
    index: 0
  orderTools:
    '00': timeTables
    '01': FileRenaming
    '02': Power
    '03': Relay
    '04': AnalyseFlexure
    index: 0
  parkMountAfterModel: false
  parkMountAfterSlew: false
  port3492: true
  posAlt0: 0.0
  posAlt1: 0.0
  posAlt2: 0.0
  posAlt3: 0.0
  posAlt4: 0.0
  posAlt5: 0.0
  posAlt6: 0.0
  posAlt7: 0.0
  posAlt8: 0.0
  posAlt9: 0.0
  posAz0: 0.0
  posAz1: 0.0
  posAz2: 0.0
  posAz3: 0.0
  posAz4: 0.0
  posAz5: 0.0
  posAz6: 0.0
  posAz7: 0.0
  posAz8: 0.0
  posAz9: 0.0
  posText0: Park Pos 0
  posText1: Park Pos 1
  posText2: Park Pos 2
  posText3: Park Pos 3
  posText4: Park Pos 4
  posText5: Park Pos 5
  posText6: Park Pos 6
  posText7: Park Pos 7
  posText8: Park Pos 8
  posText9: Park Pos 9
  progressiveTiming: false
  rackCompMAC: ''
  refracCont: false
  refracManual: true
  refracNoTrack: false
  refractionSource: ''
  relay0buttonText: ''
  relay0index: 0
  relay1buttonText: ''
  relay1index: 0
  relay2buttonText: ''
  relay2index: 0
  relay3buttonText: ''
  relay3index: 0
  relay4buttonText: ''
  relay4index: 0
  relay5buttonText: ''
  relay5index: 0
  relay6buttonText: ''
  relay6index: 0
  relay7buttonText: ''
  relay7index: 0
  rename1: 0
  rename2: 0
  rename3: 0
  rename4: 0
  rename5: 0
  rename6: 0
  renameDir: /Users/Q115346/PycharmProjects/MountWizzard4/work/image
  retriesReverse: false
  safetyMarginValue: 0.0
  satAfterFlip: true
  satAltitudeMin: 30.0
  satBeforeFlip: true
  satCyclicUpdates: false
  satFilterText: ''
  satIsSunlit: true
  satRemoveSO: true
  satSource: 1
  satTwilight: 5
  settleTimeDome: 0.0
  showTabAlmanac: true
  showTabDome: true
  showTabEnviron: true
  showTabMPC: true
  showTabParkPos: true
  showTabProfile: true
  showTabSatellite: true
  showTabTools: true
  slewSpeedHigh: false
  slewSpeedLow: true
  slewSpeedMax: false
  slewSpeedMed: false
  sortALT: false
  sortAZ: false
  sortDomeAZ: false
  soundConnectionLost: 0
  soundDomeSlewFinished: 0
  soundImageSaved: 0
  soundImageSolved: 0
  soundMountAlert: 0
  soundMountSlewFinished: 0
  soundRunFinished: 0
  soundSatStartTracking: 0
  subFrame: 100.0
  syncTimeCont: false
  syncTimeNone: true
  syncTimeNotTrack: false
  targetRMS: 10.0
  trackingReplay: false
  unitTimeLocal: false
  unitTimeUTC: true
  use10micronDef: false
  useDomeGeometry: false
  useDynamicFollowing: false
  useInternalSatCalc: false
  useOvershoot: false
  useSafetyMargin: false
  waitTimeExposure: 0.0
  waitTimeFlip: 0.0
  winPosX: 350
  winPosY: 174
measureW:
  height: 600
  set0: 0
  set1: 0
  set2: 0
  set3: 0
  set4: 0
  width: 800
  winPosX: 161
  winPosY: 162
messageW:
  height: 285
  winPosX: 356
  winPosY: 337
profileName: config
satelliteHorW:
  height: 461
  width: 743
  winPosX: 384
  winPosY: 249
satelliteMapW:
  height: 592
  width: 817
  winPosX: 347
  winPosY: 184
showAnalyseW: false
showBigPopupW: false
showHemisphereW: false
showImageW: false
showKeypadW: false
showMeasureW: false
showMessageW: false
showSatelliteHorizonW: false
showSatelliteMapW: false
showSimulatorW: false
showVideoW1: false
showVideoW2: false
showVideoW3: false
showVideoW4: false
simulatorW:
  cameraPositionX: 3.0
  cameraPositionY: 10.0
  cameraPositionZ: 3.0
  domeTransparent: true
  height: 600
  showBuildPoints: true
  showHorizon: false
  showLaser: false
  showNumbers: true
  showPointer: false
  showSlewPath: true
  width: 800
  winPosX: 356
  winPosY: 180
topoElev: 46.0
topoLat: 0.0
topoLon: 0.0
version: '4.3'
videoW1:
  frameRate: 2
  height: 580
  password: ''
  user: ''
  videoSource: 0
  videoURL: ''
  width: 780
  winPosX: 356
  winPosY: 180
