#
# v1.0, Michael Wuertenberger
#
name: install_ubuntu_head
description: installs headless setup for ubuntu

runs:
  using: 'composite'
  steps:
    -
    - name: install #0
      run: sudo apt-get update
      shell: bash

    - name: install #1
      run: sudo apt-get upgrade
      shell: bash
