# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgLoc.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InputLocation(object):
    def setupUi(self, InputLocation):
        InputLocation.setObjectName("InputLocation")
        InputLocation.setWindowModality(QtCore.Qt.NonModal)
        InputLocation.setEnabled(True)
        InputLocation.resize(250, 250)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(InputLocation.sizePolicy().hasHeightForWidth())
        InputLocation.setSizePolicy(sizePolicy)
        InputLocation.setMinimumSize(QtCore.QSize(250, 250))
        InputLocation.setMaximumSize(QtCore.QSize(250, 250))
        InputLocation.setSizeIncrement(QtCore.QSize(9, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        InputLocation.setFont(font)
        InputLocation.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        InputLocation.setFocusPolicy(QtCore.Qt.NoFocus)
        InputLocation.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        InputLocation.setToolTipDuration(6)
        InputLocation.setAutoFillBackground(True)
        self.latDeg = QtWidgets.QDoubleSpinBox(InputLocation)
        self.latDeg.setGeometry(QtCore.QRect(35, 35, 46, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.latDeg.setFont(font)
        self.latDeg.setDecimals(0)
        self.latDeg.setMinimum(-89.0)
        self.latDeg.setMaximum(89.0)
        self.latDeg.setObjectName("latDeg")
        self.ok = QtWidgets.QPushButton(InputLocation)
        self.ok.setGeometry(QtCore.QRect(30, 200, 81, 32))
        self.ok.setObjectName("ok")
        self.cancel = QtWidgets.QPushButton(InputLocation)
        self.cancel.setGeometry(QtCore.QRect(130, 200, 81, 32))
        self.cancel.setObjectName("cancel")
        self.elevation = QtWidgets.QDoubleSpinBox(InputLocation)
        self.elevation.setGeometry(QtCore.QRect(35, 155, 171, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.elevation.setFont(font)
        self.elevation.setDecimals(0)
        self.elevation.setMaximum(9000.0)
        self.elevation.setObjectName("elevation")
        self.latMin = QtWidgets.QDoubleSpinBox(InputLocation)
        self.latMin.setGeometry(QtCore.QRect(95, 35, 46, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.latMin.setFont(font)
        self.latMin.setDecimals(0)
        self.latMin.setMaximum(59.0)
        self.latMin.setObjectName("latMin")
        self.latSec = QtWidgets.QDoubleSpinBox(InputLocation)
        self.latSec.setGeometry(QtCore.QRect(160, 35, 46, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.latSec.setFont(font)
        self.latSec.setDecimals(1)
        self.latSec.setMaximum(59.9)
        self.latSec.setObjectName("latSec")
        self.lonDeg = QtWidgets.QDoubleSpinBox(InputLocation)
        self.lonDeg.setGeometry(QtCore.QRect(35, 95, 46, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lonDeg.setFont(font)
        self.lonDeg.setDecimals(0)
        self.lonDeg.setMinimum(-179.0)
        self.lonDeg.setMaximum(179.0)
        self.lonDeg.setObjectName("lonDeg")
        self.lonMin = QtWidgets.QDoubleSpinBox(InputLocation)
        self.lonMin.setGeometry(QtCore.QRect(95, 95, 46, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lonMin.setFont(font)
        self.lonMin.setDecimals(0)
        self.lonMin.setMaximum(59.0)
        self.lonMin.setObjectName("lonMin")
        self.lonSec = QtWidgets.QDoubleSpinBox(InputLocation)
        self.lonSec.setGeometry(QtCore.QRect(160, 95, 46, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lonSec.setFont(font)
        self.lonSec.setDecimals(1)
        self.lonSec.setMaximum(59.9)
        self.lonSec.setObjectName("lonSec")
        self.label = QtWidgets.QLabel(InputLocation)
        self.label.setGeometry(QtCore.QRect(35, 15, 96, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(InputLocation)
        self.label_2.setGeometry(QtCore.QRect(35, 75, 166, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(InputLocation)
        self.label_3.setGeometry(QtCore.QRect(35, 135, 81, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(InputLocation)
        QtCore.QMetaObject.connectSlotsByName(InputLocation)

    def retranslateUi(self, InputLocation):
        _translate = QtCore.QCoreApplication.translate
        InputLocation.setWindowTitle(_translate("InputLocation", "MountWizzard4 (C) MW 2018"))
        self.ok.setText(_translate("InputLocation", "OK"))
        self.cancel.setText(_translate("InputLocation", "Cancel"))
        self.label.setText(_translate("InputLocation", "Latitude"))
        self.label_2.setText(_translate("InputLocation", "Longitude East=positive"))
        self.label_3.setText(_translate("InputLocation", "Elevation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InputLocation = QtWidgets.QWidget()
    ui = Ui_InputLocation()
    ui.setupUi(InputLocation)
    InputLocation.show()
    sys.exit(app.exec_())

