#
# GitHub actions for checking the installation of MW4 through scripts
#
# v 1.0, Michael Wuertenberger
#
name: build_pyqt5_raspi

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  gh: 'https://raw.githubusercontent.com/mworion/MountWizzard4/master/support/3.0/'

on:
  push:
    # Run this action on the trigger event when specific files are touched
    paths:
      - '.github/workflows/build_pyqt5_raspi.yml'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: [aarch64]
        include:
        - arch: aarch64
          cpu: cortex-a53
          base_image: dietpi:rpi_armv8_bullseye
          cpu_info: cpuinfo/raspberrypi_zero2_w_arm64

    steps:
      - uses: pguyot/arm-runner-action@v2
        with:
          image_additional_mb: 8192
          base_image: ${{ matrix.base_image }}
          cpu: ${{ matrix.cpu }}
          cpu_info: ${{ matrix.cpu_info }}
          commands: |
            ls -la
            apt-get update
            apt-get -y upgrade
            apt-get install -y python3 python3-pip python3-dev qtbase5-dev
            apt-get install -y build-essential autoconf libtool qtwayland5
            apt-get install -y python3-pyqt5
            python3 --version
            sudo python3 -m pip install --upgrade pip
            sudo python3 -m pip install PyQt-builder==1.14.1
            sudo python3 -m pip install packaging setuptools toml wheels
            sudo python3 -m pip install pyqt5-sip
            sudo python3 -m pip install pyqt5==5.15.8 --config-settings --confirm-license= --verbose
            ls -la
