#
# v1.1, Michael Wuertenberger
#
name: unit_win

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  branch: 'master'
  cov: '--cov=mw4/ --cov-append'

on:
  push:
    # Run this action on the trigger event when specific files are touched
    paths:
      - 'mw4/**'
      - 'tests/unit_tests/**'
      - 'setup.py'
      - 'tox.ini'
      - '.github/workflows/unit_win.yml'
      - '.github/actions/build_package/action.yml'
      - '.github/actions/setup_test/action.yml'
jobs:
  build_package:
    #
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.branch}}
          
      - name: build package
        uses: ./.github/actions/build_package

  run_tests_windows_1a:
    #
    needs: build_package
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/zLoader ${{env.cov}}
          
      - name: rename_coveragefile
        run: mv .coverage c1a.dat
        
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          overwrite: true
          path: c1a.dat

  run_tests_windows_1b:
    #
    needs: build_package
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/zUpdate ${{env.cov}}
          
      - name: rename_coveragefile
        run: mv .coverage c1b.dat
        
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          overwrite: true
          path: c1b.dat

  run_tests_windows_1c:
    #
    needs: build_package
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/zMainApp ${{env.cov}}
          
      - name: rename_coveragefile
        run: mv .coverage c1c.dat
        
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          overwrite: true
          path: c1c.dat

  run_tests_windows_2a:
    #
    needs: build_package
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/base ${{env.cov}}
          pytest tests/unit_tests/logic ${{env.cov}}
          
      - name: rename_coveragefile
        run: mv .coverage c2a.dat
        
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          overwrite: true
          path: c2a.dat

  run_tests_windows_2b:
    #
    needs: build_package
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/mountcontrol ${{env.cov}}
          pytest tests/unit_tests/indibase ${{env.cov}}
          
      - name: rename_coveragefile
        run: mv .coverage c2b.dat
        
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          overwrite: true
          path: c2b.dat

  run_tests_windows_3a:
    #
    needs: build_package
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/gui/mainWindow ${{env.cov}}
          
      - name: rename_coveragefile
        run: mv .coverage c3a.dat
        
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          overwrite: true
          path: c3a.dat

  run_tests_windows_3b:
    #
    needs: build_package
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/gui/extWindows ${{env.cov}}
          
      - name: rename_coveragefile
        run: mv .coverage c3b.dat
        
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          overwrite: true
          path: c3b.dat

  run_tests_windows_3c:
    #
    needs: build_package
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/gui/utilities ${{env.cov}}
          
      - name: rename_coveragefile
        run: mv .coverage c3c.dat
        
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          overwrite: true
          path: c3c.dat

  run_tests_windows_4:
    #
    needs: build_package
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/gui/mainWmixin1 ${{env.cov}}

      - name: rename_coveragefile
        run: mv .coverage c4.dat
        
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          overwrite: true
          path: c4.dat

  run_tests_windows_5:
    #
    needs: build_package
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/gui/mainWmixin2 ${{env.cov}}

      - name: rename_coveragefile
        run: mv .coverage c5.dat
        
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          overwrite: true
          path: c5.dat

  run_tests_windows_6:
    #
    needs: build_package
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/gui/mainWmixin3 ${{env.cov}}

      - name: rename_coveragefile
        run: mv .coverage c6.dat
        
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          overwrite: true
          path: c6.dat

  coverage:
    #
    needs: [ run_tests_windows_1a, run_tests_windows_1b,
             run_tests_windows_1c, run_tests_windows_2a,
             run_tests_windows_2b, run_tests_windows_3a,
             run_tests_windows_3b, run_tests_windows_3c,
             run_tests_windows_4, run_tests_windows_5,
             run_tests_windows_6]
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{env.branch}}

    - name: combining_data
      run: |
        dir
        python -m pip install coverage
        python -m coverage combine c1a.dat c1b.dat c1c.dat c2a.dat c2b.dat c3a.dat c3b.dat c3c.dat c4.dat c5.dat c6.dat
        python -m coverage xml

    - name: upload
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml
        flags: unittests
        name: codecov-umbrella
        env_vars: OS,PYTHON
        override_branch: ${{env.branch}}
