############################################################
# -*- coding: utf-8 -*-
#
#       #   #  #   #   #    #
#      ##  ##  #  ##  #    #
#     # # # #  # # # #    #  #
#    #  ##  #  ##  ##    ######
#   #   #   #  #   #       #
#
# Python-based Tool for interaction with the 10micron mounts
# GUI with PySide6 for python3
#
# written in python3, (c) 2019-2025 by mworion
# License APL2.0
#
###########################################################
name: unit_win

concurrency:
  group: "${{ github.ref }}-${{ github.workflow }}"
  cancel-in-progress: true

env:
  cov: '--cov --cov-append --cov-config=pyproject.toml --cov-report xml:coverage.xml'

on:
  push:
    # Run this action on the trigger event when specific files are touched
    paths:
      - 'src/mw4/**'
      - 'tests/unit_tests/**'
      - 'pyproject.toml'
      - '.github/workflows/unit_win.yml'
      - '.github/actions/build_package_uv/action.yml'
      - '.github/actions/setup_test/action.yml'
      - '.github/actions/setup_test_cov/action.yml'

jobs:
  build_package:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v6
      - name: build package
        uses: ./.github/actions/build_package_uv

  run_tests_windows_0:
    needs: build_package
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v6
      - name: install package
        uses: ./.github/actions/setup_test_cov
      - name: running_unit_tests
        run: |
          uv run pytest tests/unit_tests/mainApp ${{env.cov}}
      - name: upload
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: run_tests_windows_0
          name: codecov-umbrella
          env_vars: OS,PYTHON
          override_branch: ${{env.branch}}
  
  run_tests_windows_1:
    needs: build_package
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v6
      - name: install package
        uses: ./.github/actions/setup_test_cov
      - name: running_unit_tests
        run: |
          uv run pytest tests/unit_tests/gui/mainWindow ${{env.cov}}
      - name: upload
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: run_tests_windows_1
          name: codecov-umbrella
          env_vars: OS,PYTHON
          override_branch: ${{env.branch}}

  run_tests_windows_2:
    needs: build_package
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
      - name: install package
        uses: ./.github/actions/setup_test_cov
      - name: running_unit_tests
        run: |
          uv run pytest tests/unit_tests/base ${{env.cov}}
          uv run pytest tests/unit_tests/logic ${{env.cov}}
          uv run pytest tests/unit_tests/mountcontrol ${{env.cov}}
      - name: upload
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: run_tests_windows_2
          name: codecov-umbrella
          env_vars: OS,PYTHON
          override_branch: ${{env.branch}}

  run_tests_windows_3:
    needs: build_package
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v6
      - name: install package
        uses: ./.github/actions/setup_test_cov
      - name: running_unit_tests
        run: |
          uv run pytest tests/unit_tests/gui/extWindows ${{env.cov}}
      - name: upload
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: run_tests_windows_3
          name: codecov-umbrella
          env_vars: OS,PYTHON
          override_branch: ${{env.branch}}

  run_tests_windows_4:
    needs: build_package
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
      - name: install package
        uses: ./.github/actions/setup_test_cov
      - name: running_unit_tests
        run: |
          uv run pytest tests/unit_tests/gui/utilities ${{env.cov}}
          uv run pytest tests/unit_tests/gui/styles ${{env.cov}}
          uv run pytest tests/unit_tests/gui/mainWaddon ${{env.cov}}
      - name: upload
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: run_tests_windows_4
          name: codecov-umbrella
          env_vars: OS,PYTHON
          override_branch: ${{env.branch}}
