############################################################
# -*- coding: utf-8 -*-
#
#       #   #  #   #   #    #
#      ##  ##  #  ##  #    #
#     # # # #  # # # #    #  #
#    #  ##  #  ##  ##    ######
#   #   #   #  #   #       #
#
# Python-based Tool for interaction with the 10micron mounts
# GUI with PySide6 for python3
#
# written in python3, (c) 2019-2025 by mworion
# Licence APL2.0
#
###########################################################

name: unit_win

concurrency:
  group: "${{ github.ref }}-${{ github.workflow }}"
  cancel-in-progress: true

env:
  cov: '--cov=src/mw4/ --cov-append --cov-config=pyproject.toml'

on:
  push:
    # Run this action on the trigger event when specific files are touched
    paths:
      - 'src/mw4/**'
      - 'tests/unit_tests/**'
      - 'pyproject.toml'
      - '.github/workflows/unit_win.yml'
      - '.github/actions/build_package/action.yml'
      - '.github/actions/setup_test/action.yml'
      - '.github/actions/setup_test_cov/action.yml'

jobs:
  build_package:
    #
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      
      - name: build package
        uses: ./.github/actions/build_package

  run_tests_windows_0:
    #
    needs: build_package
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/mainApp ${{env.cov}}
          
  run_tests_windows_1:
    #
    needs: build_package
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/gui/mainWindow ${{env.cov}}

  run_tests_windows_2:
    #
    needs: build_package
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/base ${{env.cov}}
          pytest tests/unit_tests/logic ${{env.cov}}
          pytest tests/unit_tests/mountcontrol ${{env.cov}}
          pytest tests/unit_tests/indibase ${{env.cov}}

  run_tests_windows_3:
    #
    needs: build_package
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/gui/extWindows ${{env.cov}}
          pytest tests/unit_tests/gui/utilities ${{env.cov}}
          pytest tests/unit_tests/gui/styles ${{env.cov}}
          pytest tests/unit_tests/gui/mainWaddon ${{env.cov}}

  run_tests_windows_4:
    #
    needs: build_package
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/gui/extWindows/video ${{env.cov}}
          pytest tests/unit_tests/gui/extWindows/image ${{env.cov}}
          pytest tests/unit_tests/gui/extWindows/hemisphere ${{env.cov}}
          pytest tests/unit_tests/gui/extWindows/simulator ${{env.cov}}
          
  coverage:
    #
    needs: [ run_tests_windows_0, run_tests_windows_1,
             run_tests_windows_2, run_tests_windows_3,
             run_tests_windows_4]
    runs-on: windows-latest
      - name: upload
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: .coverage
          flags: unittests
          name: codecov-umbrella
          env_vars: OS,PYTHON
